### ISSUE TITLE
Inference fails when outputs are not the same as inputs

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#121]
I think we are lacking coverage of this configuration. Probably we should just change our integration tests to use this setup.

```
2023-05-26T18:24:37.871559048Z Traceback (most recent call last):
2023-05-26T18:24:37.871600487Z   File "/full-model/fme/fme/fcn_training/inference/inference.py", line 532, in <module>
2023-05-26T18:24:37.871608387Z     main(
2023-05-26T18:24:37.871613487Z   File "/full-model/fme/fme/fcn_training/inference/inference.py", line 449, in main
2023-05-26T18:24:37.871619767Z     gen = torch.cat([gen_data_per_ic[i][name] for i in range(n_ics)], dim=0)
2023-05-26T18:24:37.871624907Z   File "/full-model/fme/fme/fcn_training/inference/inference.py", line 449, in <listcomp>
2023-05-26T18:24:37.871630627Z     gen = torch.cat([gen_data_per_ic[i][name] for i in range(n_ics)], dim=0)
2023-05-26T18:24:37.871635867Z KeyError: 'DSWRFtoa'
```

**Comment by mcgibbon** [comment]
Yes - while it would be ideal to test all configurations (extra inputs, extra outputs, and identical inputs/outputs), just adding additional inputs to the existing test gets us most of that coverage.
