### ISSUE TITLE
statistics files are still required by standalone inference script

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#141]
I tried running a standalone inference experiment without the stats mounted, and it failed. We should be able to load the statistics from the serialized stepper, but we need to tell the stepper to do so when it is initialized in the inference script.

beaker experiment: https://beaker.org/ex/01H3ZQ9RRSDCFA9Y2595GGSNXM/tasks/01H3ZQ9RRWT3C203DN5GMC3W5P/job/01H3ZQA22ATMPN9GBWTHBZ1CJA

Traceback:
```
2023-06-28T00:45:28.752575262Z Traceback (most recent call last):
2023-06-28T00:45:28.752603542Z   File "/full-model/fme/fme/fcn_training/inference/inference.py", line 184, in <module>
2023-06-28T00:45:28.752611041Z     main(
2023-06-28T00:45:28.752616171Z   File "/full-model/fme/fme/fcn_training/inference/inference.py", line 109, in main
2023-06-28T00:45:28.752621591Z     stepper = config.load_stepper()
2023-06-28T00:45:28.752626671Z   File "/full-model/fme/fme/fcn_training/inference/inference.py", line 83, in load_stepper
2023-06-28T00:45:28.752632871Z     return load_stepper(self.checkpoint_path)
2023-06-28T00:45:28.752638401Z   File "/full-model/fme/fme/fcn_training/inference/inference.py", line 29, in load_stepper
2023-06-28T00:45:28.752643701Z     stepper = SingleModuleStepper.from_state(
2023-06-28T00:45:28.752648631Z   File "/full-model/fme/fme/core/stepper.py", line 275, in from_state
2023-06-28T00:45:28.752668141Z     stepper = cls(
2023-06-28T00:45:28.752673221Z   File "/full-model/fme/fme/core/stepper.py", line 106, in __init__
2023-06-28T00:45:28.752678351Z     self.normalizer = config.normalization.build(config.all_names)
2023-06-28T00:45:28.752683451Z   File "/full-model/fme/fme/core/normalizer.py", line 38, in build
2023-06-28T00:45:28.752688591Z     return get_normalizer(
2023-06-28T00:45:28.752693521Z   File "/full-model/fme/fme/core/normalizer.py", line 111, in get_normalizer
2023-06-28T00:45:28.752698701Z     means = load_Dict_from_netcdf(global_means_path, names)
2023-06-28T00:45:28.752703691Z   File "/full-model/fme/fme/core/normalizer.py", line 119, in load_Dict_from_netcdf
2023-06-28T00:45:28.752709871Z     ds = netCDF4.Dataset(path)
2023-06-28T00:45:28.752714741Z   File "src/netCDF4/_netCDF4.pyx", line 2449, in netCDF4._netCDF4.Dataset.__init__
2023-06-28T00:45:28.752719971Z   File "src/netCDF4/_netCDF4.pyx", line 2012, in netCDF4._netCDF4._ensure_nc_success
2023-06-28T00:45:28.752725201Z FileNotFoundError: [Errno 2] No such file or directory: '/statsdata/fv3gfs-mean.nc'
```

**Comment by oliverwm1** [comment]
I think this was resolved by https://github.com/ai2cm/full-model/pull/189
