### ISSUE TITLE
Installing `fme` from GH url not successful

### ISSUE THREAD

**Issue by brianhenn** [ai2cm/ace#15]
This repo's docs recommend installing `fme` via pip from this repo's GH url. 

```pip install git+https://github.com/ai2cm/ace#subdirectory=fme```

However this results in failure to import `fme`:

```
(ace) brianh@brian-vm:~/dev$ python -c "import fme"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/brianh/miniconda3/envs/my_env/lib/python3.10/site-packages/fme/__init__.py", line 5, in <module>
    from . import ace
  File "/home/brianh/miniconda3/envs/my_env/lib/python3.10/site-packages/fme/ace/__init__.py", line 3, in <module>
    from fme.ace.inference.data_writer.time_coarsen import TimeCoarsenConfig
  File "/home/brianh/miniconda3/envs/my_env/lib/python3.10/site-packages/fme/ace/inference/__init__.py", line 1, in <module>
    from .loop import run_inference_evaluator
  File "/home/brianh/miniconda3/envs/my_env/lib/python3.10/site-packages/fme/ace/inference/loop.py", line 9, in <module>
    from fme.core import SingleModuleStepper
  File "/home/brianh/miniconda3/envs/my_env/lib/python3.10/site-packages/fme/core/__init__.py", line 1, in <module>
    from .climate_data import ClimateData
  File "/home/brianh/miniconda3/envs/my_env/lib/python3.10/site-packages/fme/core/climate_data.py", line 15, in <module>
    from fme.core.data_loading.data_typing import SigmaCoordinates
ModuleNotFoundError: No module named 'fme.core.data_loading'

**Comment by oliverwm1** [comment]
FYI current workaround is to clone repository and install from sources (e.g. call `make create_environment`).

**Comment by oliverwm1** [comment]
This might be because of a missing `__init__.py` in `fme.core.data_loading`.
