### ISSUE TITLE
`fme` missing attribute 'get_device' on clean install

### ISSUE THREAD

**Issue by ngordillo** [ai2cm/ace#22]
Doing a clean install of ACE and creating the environment, the fme module is missing elements needed to run. I've tested this out on two different machines get the same error message.
```
Traceback (most recent call last):
  File "/home/nicojg/mambaforge/envs/fme/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/nicojg/mambaforge/envs/fme/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/nicojg/ace/fme/fme/ace/inference/__main__.py", line 8, in <module>
    main(yaml_config=args.yaml_config)
  File "/home/nicojg/ace/fme/fme/ace/inference/inference.py", line 221, in main
    run_inference_from_config(config)
  File "/home/nicojg/ace/fme/fme/ace/inference/inference.py", line 235, in run_inference_from_config
    logging.info(f"Current device is {fme.get_device()}")
AttributeError: module 'fme' has no attribute 'get_device'
```
I managed to work around this by uninstalling fme after running `make create_environment` and then reinstalling to the latest version.

**Comment by oliverwm1** [comment]
Thanks for reporting. I am not able to reproduce this so far.

Do you also have the issue if installing directly from PyPI?

**Comment by oliverwm1** [comment]
I was able to reproduce this. It happens specifically when in the root directory of this repo (e.g. call `python -c "import fme; fme.get_device()"` from root dir of the repo). But does not happen when running the command elsewhere.

**Comment by ngordillo** [comment]
I did a clean install of ACE on a system that didn't have mamba installed and it worked following the quick start guide on the first attempt. So I am inclined to believe that this is an issue with mamba.

**Comment by frodre** [comment]
Turns out this is related to our usage of a development install `-e` and there being an `fme` folder in the top level that's not the actual package source folder `fme/fme`.  Python path includes the local directory by default in `sys.path` and searches there first, so it finds the top-level `fme` assumes it's the package but then finds no submodules.

```
Python 3.10.16 (main, Dec 11 2024, 16:24:50) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fme
>>> fme.get_device()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'fme' has no attribute 'get_device'
>>> 
```

If I remove the current working directory from `sys.path`, the error goes away.

```
Python 3.10.16 (main, Dec 11 2024, 16:24:50) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', '/home/andrep/miniconda3/envs/fme/lib/python310.zip', '/home/andrep/miniconda3/envs/fme/lib/python3.10', '/home/andrep/miniconda3/envs/fme/lib/python3.10/lib-dynload', '/home/andrep/miniconda3/envs/fme/lib/python3.10/site-packages', '__editable__.fme-2024.12.0.finder.__path_hook__']
>>> del sys.path[0]
>>> import fme
>>> fme.get_device()
device(type='cpu')
>>> 
```

We'll just have to update the folder naming convention so this won't bite others looking to do local dev work in this repo.

**Comment by oliverwm1** [comment]
@elynnwu found a nice workaround for now. Add `-I` to the python invocation, and things should work.

i.e. in the root dir of the repo, `python -c "import fme; fme.get_device()"` fails but `python -I -c "import fme; fme.get_device()"` works.

**Comment by oliverwm1** [comment]
This was resolved by #31 in which we removed one "fme" layer in the directory structure of this repo. i.e. now the `fme` python package lives at the root of the repo instead of within a `fme` directory.
