### ISSUE TITLE
Shared memory runs out while computing inline inference metrics

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#330]
Even though I had configured 80GiB of shared memory, I got the following error ([beaker job](https://beaker.org/ex/01HVYKPADQDQGZ96M3HX8HPK1G/tasks/01HVYKPADWHCP3PDKVC6SX9Z5P/job/01HVYKPBTJQ8QGTWK8MKPJACCV)). I was able to resolve it by making "forward_steps_in_memory" smaller. But I'm confused that this is complaining about a 'data loader''s worker is running out of memory.

```
2024-04-20T23:58:16.088643372Z 2024-04-20 23:58:16,087 - root - INFO - Inference: starting window spanning 0 to 146 steps, out of total 7446.
2024-04-20T23:58:25.462766653Z ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
2024-04-20T23:58:25.462862770Z �ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
2024-04-20T23:58:25.462871954Z �ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
2024-04-20T23:58:25.462878908Z �ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
2024-04-20T23:58:25.462885129Z �ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
2024-04-20T23:58:25.462891409Z �ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
2024-04-20T23:58:25.462897378Z �ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
2024-04-20T23:58:25.462903678Z �ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
2024-04-20T23:58:25.462909695Z �ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
2024-04-20T23:58:25.462915667Z �ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
2024-04-20T23:58:25.462921502Z �ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
2024-04-20T23:58:25.462927349Z �ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
2024-04-20T23:58:25.462933279Z �ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
2024-04-20T23:58:25.462939569Z �ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
2024-04-20T23:58:29.659374959Z �Traceback (most recent call last):
2024-04-20T23:58:29.659439820Z   File "/full-model/fme/fme/ace/train.py", line 499, in <module>
2024-04-20T23:58:29.659638448Z     main(yaml_config=args.yaml_config)
2024-04-20T23:58:29.659693456Z   File "/full-model/fme/fme/ace/train.py", line 490, in main
2024-04-20T23:58:29.659703160Z     trainer.train()
2024-04-20T23:58:29.659711196Z   File "/full-model/fme/fme/ace/train.py", line 208, in train
2024-04-20T23:58:29.659726568Z     inference_logs = self.inference_one_epoch()
2024-04-20T23:58:29.659733130Z   File "/full-model/fme/fme/ace/train.py", line 379, in inference_one_epoch
2024-04-20T23:58:29.659755577Z     run_inference(
2024-04-20T23:58:29.659770068Z   File "/full-model/fme/fme/ace/inference/loop.py", line 190, in run_inference
2024-04-20T23:58:29.659833783Z     _inference_internal_loop(
2024-04-20T23:58:29.659840825Z   File "/full-model/fme/fme/ace/inference/loop.py", line 123, in _inference_internal_loop
2024-04-20T23:58:29.659847513Z     aggregator.record_batch(
2024-04-20T23:58:29.659853984Z   File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
2024-04-20T23:58:29.659860770Z     return func(*args, **kwargs)
2024-04-20T23:58:29.659867622Z   File "/full-model/fme/fme/core/aggregator/inference/main.py", line 196, in record_batch
2024-04-20T23:58:29.659877966Z     time_dependent_aggregator.record_batch(
2024-04-20T23:58:29.659884314Z   File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
2024-04-20T23:58:29.659891252Z     return func(*args, **kwargs)
2024-04-20T23:58:29.659897059Z   File "/full-model/fme/fme/core/aggregator/inference/seasonal.py", line 42, in record_batch
2024-04-20T23:58:29.659950409Z     self._target_dataset = target_ds.groupby(
2024-04-20T23:58:29.659983929Z   File "/opt/conda/lib/python3.8/site-packages/xarray/core/_aggregations.py", line 3178, in sum
2024-04-20T23:58:29.660336924Z     return self.reduce(
2024-04-20T23:58:29.660346532Z   File "/opt/conda/lib/python3.8/site-packages/xarray/core/groupby.py", line 1363, in reduce
2024-04-20T23:58:29.660470945Z     return self.map(reduce_dataset)
2024-04-20T23:58:29.660479676Z   File "/opt/conda/lib/python3.8/site-packages/xarray/core/groupby.py", line 1272, in map
2024-04-20T23:58:29.660585213Z     return self._combine(applied)
2024-04-20T23:58:29.660590686Z   File "/opt/conda/lib/python3.8/site-packages/xarray/core/groupby.py", line 1292, in _combine
2024-04-20T23:58:29.660686713Z     applied_example, applied = peek_at(applied)
2024-04-20T23:58:29.660691487Z   File "/opt/conda/lib/python3.8/site-packages/xarray/core/utils.py", line 186, in peek_at
2024-04-20T23:58:29.660725005Z     peek = next(gen)
2024-04-20T23:58:29.660728789Z   File "/opt/conda/lib/python3.8/site-packages/xarray/core/groupby.py", line 1271, in <genexpr>
2024-04-20T23:58:29.660841289Z     applied = (func(ds, *args, **kwargs) for ds in self._iter_grouped())
2024-04-20T23:58:29.660845891Z   File "/opt/conda/lib/python3.8/site-packages/xarray/core/groupby.py", line 562, in _iter_grouped
2024-04-20T23:58:29.660888746Z     yield self._obj.isel({self._group_dim: indices})
2024-04-20T23:58:29.660893103Z   File "/opt/conda/lib/python3.8/site-packages/xarray/core/dataset.py", line 2446, in isel
2024-04-20T23:58:29.661123973Z     var = var.isel(var_indexers)
2024-04-20T23:58:29.661127986Z   File "/opt/conda/lib/python3.8/site-packages/xarray/core/variable.py", line 1321, in isel
2024-04-20T23:58:29.661278076Z     return self[key]
2024-04-20T23:58:29.661281962Z   File "/opt/conda/lib/python3.8/site-packages/xarray/core/variable.py", line 869, in __getitem__
2024-04-20T23:58:29.661397202Z     data = as_indexable(self._data)[indexer]
2024-04-20T23:58:29.661410158Z   File "/opt/conda/lib/python3.8/site-packages/xarray/core/indexing.py", line 1269, in __getitem__
2024-04-20T23:58:29.661519019Z     return array[key]
2024-04-20T23:58:29.661528116Z   File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
2024-04-20T23:58:29.661563828Z     _error_if_any_worker_fails()
2024-04-20T23:58:29.661567752Z RuntimeError: DataLoader worker (pid 7731) is killed by signal: Bus error. It is possible that dataloader's workers are out of shared memory. Please try to raise your shared memory limit.

```

**Comment by mcgibbon** [comment]
Is this on our own cluster or another cluster (beaker website is down right now so I can't check)? I ran into an out of memory issue the other week and in talking with beaker folks learned memory limits are (sometimes? always? not sure) not strictly imposed, such that one job could possibly use all the memory on a node causing other jobs to fail.

**Comment by oliverwm1** [comment]
I'm going to close this, since it was resolved by decreasing `forward_steps_in_memory` and we've updated the example config to use a smaller value (50).
