### ISSUE TITLE
Error during histogram calculation

### ISSUE THREAD

**Issue by mcgibbon** [ai2cm/ace#342]
Since optimizing the histogram calculations for performance using bincount, sometimes they cause runs to fail with an error (for example [this run](https://beaker.org/ex/01HWR738AAFR2085J8NHRR6M20)):
```
2024-04-30T21:42:24.196614501Z Traceback (most recent call last):
2024-04-30T21:42:24.196672621Z   File "/full-model/fme/fme/ace/train.py", line 492, in <module>
2024-04-30T21:42:24.196682334Z     main(yaml_config=args.yaml_config)
2024-04-30T21:42:24.196696582Z   File "/full-model/fme/fme/ace/train.py", line 483, in main
2024-04-30T21:42:24.196703308Z     trainer.train()
2024-04-30T21:42:24.196719808Z   File "/full-model/fme/fme/ace/train.py", line 200, in train
2024-04-30T21:42:24.196726268Z     inference_logs = self.inference_one_epoch()
2024-04-30T21:42:24.196774866Z   File "/full-model/fme/fme/ace/train.py", line 372, in inference_one_epoch
2024-04-30T21:42:24.196782056Z     run_inference(
2024-04-30T21:42:24.196830376Z   File "/full-model/fme/fme/ace/inference/loop.py", line 194, in run_inference
2024-04-30T21:42:24.196869856Z     _inference_internal_loop(
2024-04-30T21:42:24.196890003Z   File "/full-model/fme/fme/ace/inference/loop.py", line 119, in _inference_internal_loop
2024-04-30T21:42:24.196897398Z     aggregator.record_batch(
2024-04-30T21:42:24.196903414Z   File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
2024-04-30T21:42:24.196910138Z     return func(*args, **kwargs)
2024-04-30T21:42:24.196917778Z   File "/full-model/fme/fme/core/aggregator/inference/main.py", line 209, in record_batch
2024-04-30T21:42:24.196924167Z     aggregator.record_batch(
2024-04-30T21:42:24.196951522Z   File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
2024-04-30T21:42:24.196962496Z     return func(*args, **kwargs)
2024-04-30T21:42:24.196984377Z   File "/full-model/fme/fme/core/aggregator/inference/histogram.py", line 22, in record_batch
2024-04-30T21:42:24.196993103Z     self._histograms.record_batch(target_data, gen_data)
2024-04-30T21:42:24.197026655Z   File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
2024-04-30T21:42:24.197035291Z     return func(*args, **kwargs)
2024-04-30T21:42:24.197054255Z   File "/full-model/fme/fme/core/histogram.py", line 196, in record_batch
2024-04-30T21:42:24.197062795Z     self.prediction_histograms[k].add(prediction[k].flatten().unsqueeze(0))
2024-04-30T21:42:24.197077039Z   File "/full-model/fme/fme/core/histogram.py", line 111, in add
2024-04-30T21:42:24.197083287Z     histogram(
2024-04-30T21:42:24.197118603Z   File "/full-model/fme/fme/core/histogram.py", line 55, in histogram
2024-04-30T21:42:24.197125199Z     counts = torch.bincount(((arr - vmin) / bin_size).int(), minlength=n_bins)
2024-04-30T21:42:24.197170910Z RuntimeError: bincount only supports 1-d non-negative integral inputs.
```

This is likely some kind of rounding issue, though I don't really see how any value in `arr` could be less than `vmin`. This particular error could probably be fixed by setting the bin values to max(0, value).

**Comment by oliverwm1** [comment]
I just hit this in Run ai2cm/ace#61 of this beaker experiment: https://beaker.org/ex/01J0SV5HWFXR61FPN5ANW9ZCYD/tasks/01J0SV5HWNNX2D72NVRXPKQ2TN/job/01J0VRW2VM3NNANYRM48TNHMAH

Full traceback:
```
2024-06-21T23:42:26.285529725Z 2024-06-21 23:42:26,284 - root - INFO - Inference: starting window spanning 1080 to 1120 steps, out of total 7300.
2024-06-21T23:42:29.631502800Z Traceback (most recent call last):
2024-06-21T23:42:29.631540550Z   File "/full-model/fme/fme/ace/train.py", line 525, in <module>
2024-06-21T23:42:29.631542839Z     main(yaml_config=args.yaml_config)
2024-06-21T23:42:29.631544449Z   File "/full-model/fme/fme/ace/train.py", line 515, in main
2024-06-21T23:42:29.631545920Z     trainer.train()
2024-06-21T23:42:29.631547472Z   File "/full-model/fme/fme/ace/train.py", line 213, in train
2024-06-21T23:42:29.631548705Z     inference_logs = self.inference_one_epoch()
2024-06-21T23:42:29.631550044Z   File "/full-model/fme/fme/ace/train.py", line 391, in inference_one_epoch
2024-06-21T23:42:29.631551431Z     run_inference_evaluator(
2024-06-21T23:42:29.631552628Z   File "/full-model/fme/fme/ace/inference/loop.py", line 283, in run_inference_evaluator
2024-06-21T23:42:29.631565063Z     _inference_internal_loop(stepped, i_time, aggregator, stitcher, batch_times)
2024-06-21T23:42:29.631566369Z   File "/full-model/fme/fme/ace/inference/loop.py", line 146, in _inference_internal_loop
2024-06-21T23:42:29.631567733Z     aggregator.record_batch(
2024-06-21T23:42:29.631568858Z   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2024-06-21T23:42:29.631570445Z     return func(*args, **kwargs)
2024-06-21T23:42:29.631571594Z   File "/full-model/fme/fme/core/aggregator/inference/main.py", line 249, in record_batch
2024-06-21T23:42:29.631573088Z     aggregator.record_batch(
2024-06-21T23:42:29.631574203Z   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2024-06-21T23:42:29.631575623Z     return func(*args, **kwargs)
2024-06-21T23:42:29.631576761Z   File "/full-model/fme/fme/core/aggregator/inference/histogram.py", line 22, in record_batch
2024-06-21T23:42:29.631578169Z     self._histograms.record_batch(target_data, gen_data)
2024-06-21T23:42:29.631579414Z   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2024-06-21T23:42:29.631580803Z     return func(*args, **kwargs)
2024-06-21T23:42:29.631582049Z   File "/full-model/fme/fme/core/histogram.py", line 196, in record_batch
2024-06-21T23:42:29.631583256Z     self.prediction_histograms[k].add(prediction[k].flatten().unsqueeze(0))
2024-06-21T23:42:29.631584662Z   File "/full-model/fme/fme/core/histogram.py", line 111, in add
2024-06-21T23:42:29.631585951Z     histogram(
2024-06-21T23:42:29.631587191Z   File "/full-model/fme/fme/core/histogram.py", line 55, in histogram
2024-06-21T23:42:29.631588421Z     counts = torch.bincount(((arr - vmin) / bin_size).int(), minlength=n_bins)
2024-06-21T23:42:29.631589810Z RuntimeError: bincount only supports 1-d non-negative integral inputs.
2024-06-21T23:42:29.674466794Z 2024-06-21 23:42:29,674 - root - INFO - Inference: starting window spanning 1120 to 1160 steps, out of total 7300.
2024-06-21T23:42:33.615695146Z Traceback (most recent call last):
2024-06-21T23:42:33.615736374Z   File "/full-model/fme/fme/ace/train.py", line 525, in <module>
2024-06-21T23:42:33.615738891Z     main(yaml_config=args.yaml_config)
2024-06-21T23:42:33.615740601Z   File "/full-model/fme/fme/ace/train.py", line 515, in main
2024-06-21T23:42:33.615742094Z     trainer.train()
2024-06-21T23:42:33.615743650Z   File "/full-model/fme/fme/ace/train.py", line 213, in train
2024-06-21T23:42:33.615744974Z     inference_logs = self.inference_one_epoch()
2024-06-21T23:42:33.615746488Z   File "/full-model/fme/fme/ace/train.py", line 391, in inference_one_epoch
2024-06-21T23:42:33.615747833Z     run_inference_evaluator(
2024-06-21T23:42:33.615758815Z   File "/full-model/fme/fme/ace/inference/loop.py", line 283, in run_inference_evaluator
2024-06-21T23:42:33.615760344Z     _inference_internal_loop(stepped, i_time, aggregator, stitcher, batch_times)
2024-06-21T23:42:33.615761888Z   File "/full-model/fme/fme/ace/inference/loop.py", line 146, in _inference_internal_loop
2024-06-21T23:42:33.615763210Z     aggregator.record_batch(
2024-06-21T23:42:33.615764544Z   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2024-06-21T23:42:33.615765909Z     return func(*args, **kwargs)
2024-06-21T23:42:33.615767280Z   File "/full-model/fme/fme/core/aggregator/inference/main.py", line 249, in record_batch
2024-06-21T23:42:33.615768601Z     aggregator.record_batch(
2024-06-21T23:42:33.615770128Z   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2024-06-21T23:42:33.615771426Z     return func(*args, **kwargs)
2024-06-21T23:42:33.615772885Z   File "/full-model/fme/fme/core/aggregator/inference/histogram.py", line 22, in record_batch
2024-06-21T23:42:33.615774186Z     self._histograms.record_batch(target_data, gen_data)
2024-06-21T23:42:33.615775608Z   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2024-06-21T23:42:33.615776893Z     return func(*args, **kwargs)
2024-06-21T23:42:33.615778076Z   File "/full-model/fme/fme/core/histogram.py", line 196, in record_batch
2024-06-21T23:42:33.615779709Z     self.prediction_histograms[k].add(prediction[k].flatten().unsqueeze(0))
2024-06-21T23:42:33.615781036Z   File "/full-model/fme/fme/core/histogram.py", line 111, in add
2024-06-21T23:42:33.615782364Z     histogram(
2024-06-21T23:42:33.615783632Z   File "/full-model/fme/fme/core/histogram.py", line 55, in histogram
2024-06-21T23:42:33.615784880Z     counts = torch.bincount(((arr - vmin) / bin_size).int(), minlength=n_bins)
2024-06-21T23:42:33.615786182Z RuntimeError: bincount only supports 1-d non-negative integral inputs.
2024-06-21T23:42:37.418080378Z Traceback (most recent call last):
2024-06-21T23:42:37.418107980Z   File "/full-model/fme/fme/ace/train.py", line 525, in <module>
2024-06-21T23:42:37.418111050Z     main(yaml_config=args.yaml_config)
2024-06-21T23:42:37.418112506Z   File "/full-model/fme/fme/ace/train.py", line 515, in main
2024-06-21T23:42:37.418113886Z     trainer.train()
2024-06-21T23:42:37.418115189Z   File "/full-model/fme/fme/ace/train.py", line 213, in train
2024-06-21T23:42:37.418116470Z     inference_logs = self.inference_one_epoch()
2024-06-21T23:42:37.418117919Z   File "/full-model/fme/fme/ace/train.py", line 391, in inference_one_epoch
2024-06-21T23:42:37.418119230Z     run_inference_evaluator(
2024-06-21T23:42:37.418120546Z   File "/full-model/fme/fme/ace/inference/loop.py", line 283, in run_inference_evaluator
2024-06-21T23:42:37.418132289Z     _inference_internal_loop(stepped, i_time, aggregator, stitcher, batch_times)
2024-06-21T23:42:37.418133834Z   File "/full-model/fme/fme/ace/inference/loop.py", line 146, in _inference_internal_loop
2024-06-21T23:42:37.418135137Z     aggregator.record_batch(
2024-06-21T23:42:37.418136576Z   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2024-06-21T23:42:37.418137934Z     return func(*args, **kwargs)
2024-06-21T23:42:37.418139233Z   File "/full-model/fme/fme/core/aggregator/inference/main.py", line 249, in record_batch
2024-06-21T23:42:37.418140546Z     aggregator.record_batch(
2024-06-21T23:42:37.418141822Z   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2024-06-21T23:42:37.418143186Z     return func(*args, **kwargs)
2024-06-21T23:42:37.418144646Z   File "/full-model/fme/fme/core/aggregator/inference/histogram.py", line 22, in record_batch
2024-06-21T23:42:37.418145943Z     self._histograms.record_batch(target_data, gen_data)
2024-06-21T23:42:37.418147310Z   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2024-06-21T23:42:37.418148628Z     return func(*args, **kwargs)
2024-06-21T23:42:37.418149955Z   File "/full-model/fme/fme/core/histogram.py", line 196, in record_batch
2024-06-21T23:42:37.418151207Z     self.prediction_histograms[k].add(prediction[k].flatten().unsqueeze(0))
2024-06-21T23:42:37.418152586Z   File "/full-model/fme/fme/core/histogram.py", line 111, in add
2024-06-21T23:42:37.418153866Z     histogram(
2024-06-21T23:42:37.418155178Z   File "/full-model/fme/fme/core/histogram.py", line 55, in histogram
2024-06-21T23:42:37.418156495Z     counts = torch.bincount(((arr - vmin) / bin_size).int(), minlength=n_bins)
2024-06-21T23:42:37.418157874Z RuntimeError: bincount only supports 1-d non-negative integral inputs.
2024-06-21T23:42:38.177655360Z Traceback (most recent call last):
2024-06-21T23:42:38.177817657Z   File "/full-model/fme/fme/ace/train.py", line 525, in <module>
2024-06-21T23:42:38.177821742Z     main(yaml_config=args.yaml_config)
2024-06-21T23:42:38.178010915Z   File "/full-model/fme/fme/ace/train.py", line 515, in main
2024-06-21T23:42:38.178012914Z     trainer.train()
2024-06-21T23:42:38.178180305Z   File "/full-model/fme/fme/ace/train.py", line 213, in train
2024-06-21T23:42:38.178182280Z     inference_logs = self.inference_one_epoch()
2024-06-21T23:42:38.178357958Z   File "/full-model/fme/fme/ace/train.py", line 391, in inference_one_epoch
2024-06-21T23:42:38.178359903Z     run_inference_evaluator(
2024-06-21T23:42:38.178535610Z   File "/full-model/fme/fme/ace/inference/loop.py", line 283, in run_inference_evaluator
2024-06-21T23:42:38.178547253Z     _inference_internal_loop(stepped, i_time, aggregator, stitcher, batch_times)
2024-06-21T23:42:38.178733027Z   File "/full-model/fme/fme/ace/inference/loop.py", line 146, in _inference_internal_loop
2024-06-21T23:42:38.178749435Z     aggregator.record_batch(
2024-06-21T23:42:38.178899462Z   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2024-06-21T23:42:38.178903291Z     return func(*args, **kwargs)
2024-06-21T23:42:38.179066314Z   File "/full-model/fme/fme/core/aggregator/inference/main.py", line 249, in record_batch
2024-06-21T23:42:38.179068143Z     aggregator.record_batch(
2024-06-21T23:42:38.179240858Z   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2024-06-21T23:42:38.179243978Z     return func(*args, **kwargs)
2024-06-21T23:42:38.179409449Z   File "/full-model/fme/fme/core/aggregator/inference/histogram.py", line 22, in record_batch
2024-06-21T23:42:38.179412225Z     self._histograms.record_batch(target_data, gen_data)
2024-06-21T23:42:38.179581606Z   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2024-06-21T23:42:38.179584179Z     return func(*args, **kwargs)
2024-06-21T23:42:38.179749523Z   File "/full-model/fme/fme/core/histogram.py", line 196, in record_batch
2024-06-21T23:42:38.179751777Z     self.prediction_histograms[k].add(prediction[k].flatten().unsqueeze(0))
2024-06-21T23:42:38.179920129Z   File "/full-model/fme/fme/core/histogram.py", line 111, in add
2024-06-21T23:42:38.179922218Z     histogram(
2024-06-21T23:42:38.180086081Z   File "/full-model/fme/fme/core/histogram.py", line 55, in histogram
2024-06-21T23:42:38.180087780Z     counts = torch.bincount(((arr - vmin) / bin_size).int(), minlength=n_bins)
2024-06-21T23:42:38.180261421Z RuntimeError: bincount only supports 1-d non-negative integral inputs.
```

**Comment by oliverwm1** [comment]
It was in a run that seemed to be going unstable in the previous couple epochs (https://wandb.ai/ai2cm/fourcastnet/runs/aa335egf?nw=nwuseroliverwm). Maybe it happens when there are NaNs in the generated outputs?

**Comment by oliverwm1** [comment]
I've hit this in a few other runs. All cases were like one above where inference was going unstable in the preceding epochs. So I suspect it is due to NaNs in the predictions. I think we should just have a try/except and not compute or log the histogram if the RuntimeError happens.

**Comment by mcgibbon** [comment]
I'm good with a try-except, since it doesn't seem to be happening on "normal" runs. Will work on a PR.

**Comment by mcgibbon** [comment]
PR should do something similar to that: https://github.com/ai2cm/full-model/pull/825

It will still report a histogram rather than not logging it, which may or may not be desirable. Can comment in review.
