### ISSUE TITLE
RestartWriter leads to failed tmpdir cleanup when running tests

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#344]
Since ai2cm/full-model#775, running the data writer tests leads to many warnings like this:
```
fme/fme/ace/inference/data_writer/test_data_writer.py::TestDataWriter::test_append_batch[julian]
  /opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/_pytest/unraisableexception.py:80: PytestUnraisableExceptionWarning: Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7f401b712050>
  
  Traceback (most recent call last):
    File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/tempfile.py", line 466, in __del__
      self.close()
    File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/tempfile.py", line 462, in close
      unlink(self.name)
  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp1xmo8yat'
  
    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))
```

This is likely coming from the tempfile used when overwriting existing restarts:

https://github.com/ai2cm/full-model/blob/e04d95273e326c217e84f1f7e9397e9da1f11915/fme/fme/ace/inference/data_writer/restart.py#L92-L102

**Comment by oliverwm1** [comment]
This was resolved by ai2cm/full-model#797
