### ISSUE TITLE
Perlmutter segfault appears on some commits with 23.08 base image

### ISSUE THREAD

**Issue by brianhenn** [ai2cm/ace#346]
Of about a dozen commits/images I've tested since bumping the pytorch base image to 23.08, none have triggered the segfault, until [this one](https://github.com/ai2cm/full-model/commit/cd02721a810afcac7826ac8a7a52711201cd58b1) did ([wandb run](https://wandb.ai/ai2cm/fourcastnet/runs/yqt9h2uv)). See error below. This appears to be "deterministic" in the sense that commits to the full-model code either trigger the segfault, or they don't. Perhaps this dependence on full-model commits gives a path to figuring out the cause.

```
+ export FME_OUTPUT_DIR=/pscratch/sd/b/bhenn/fme-output/25244315
+ FME_OUTPUT_DIR=/pscratch/sd/b/bhenn/fme-output/25244315
+ mkdir -p /pscratch/sd/b/bhenn/fme-output/25244315
+ export WANDB_JOB_TYPE=training
+ WANDB_JOB_TYPE=training
+ set +x
+ cp -r /pscratch/sd/b/bhenn/fme-config/51d2e45a-cf30-4006-8a78-72e0e7e7e6ea /pscratch/sd/b/bhenn/fme-output/25244315/job_config
+ srun -u /pscratch/sd/b/bhenn/fme-config/51d2e45a-cf30-4006-8a78-72e0e7e7e6ea/requeueable-train.sh
+ pid=920031
+ trap 'preempt_handler '\''920031'\''' SIGTERM
+ trap 'timeout_handler '\''920031'\''' USR1
+ wait
+ podman-hpc run --rm --gpu --ipc host -v /pscratch/sd/b/bhenn/fme-config/51d2e45a-cf30-4006-8a78-72e0e7e7e6ea:/configmount -v /pscratch/sd/b/bhenn/data/2023-11-01-subset-vertically-resolved-1deg-fme-amip-ensemble-dataset/train:/traindata -v /pscratch/sd/b/bhenn/data/2023-11-01-subset-vertically-resolved-1deg-fme-amip-ensemble-dataset/validation/ic_0002:/validdata -v /pscratch/sd/b/bhenn/data/2023-11-01-vertically-resolved-1deg-fme-amip-ensemble-dataset-stats/residual:/statsdata -v /pscratch/sd/b/bhenn/fme-output/25244315:/output --env 'WANDB*' --env 'SLURM*' --env 'FME*' fme:ff6ac271 torchrun --nproc_per_node 1 /full-model/fme/fme/ace/train.py --yaml_config /configmount/train-config.yaml

=============
== PyTorch ==
=============

NVIDIA Release 23.08 (build 66128610)
PyTorch Version 2.1.0a0+29c30b1

Container image Copyright (c) 2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

Copyright (c) 2014-2023 Facebook Inc.
Copyright (c) 2011-2014 Idiap Research Institute (Ronan Collobert)
Copyright (c) 2012-2014 Deepmind Technologies    (Koray Kavukcuoglu)
Copyright (c) 2011-2012 NEC Laboratories America (Koray Kavukcuoglu)
Copyright (c) 2011-2013 NYU                      (Clement Farabet)
Copyright (c) 2006-2010 NEC Laboratories America (Ronan Collobert, Leon Bottou, Iain Melvin, Jason Weston)
Copyright (c) 2006      Idiap Research Institute (Samy Bengio)
Copyright (c) 2001-2004 Idiap Research Institute (Ronan Collobert, Samy Bengio, Johnny Mariethoz)
Copyright (c) 2015      Google Inc.
Copyright (c) 2015      Yangqing Jia
Copyright (c) 2013-2016 The Caffe contributors
All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

NOTE: CUDA Forward Compatibility mode ENABLED.
  Using CUDA 12.2 driver version 535.86.10 with kernel driver version 525.105.17.
  See https://docs.nvidia.com/deploy/cuda-compatibility/ for details.

2024-05-06 07:29:29,750 - root - WARNING - Environmental variable BEAKER_EXPERIMENT_ID not found.
2024-05-06 07:29:29,751 - root - INFO - Environmental variable SLURM_JOB_ID=25244315.
2024-05-06 07:29:29,751 - root - INFO - Environmental variable SLURM_JOB_USER=bhenn.
2024-05-06 07:29:29,751 - root - INFO - Environmental variable FME_TRAIN_DIR=/pscratch/sd/b/bhenn/data/2023-11-01-subset-vertically-resolved-1deg-fme-amip-ensemble-dataset/train.
2024-05-06 07:29:29,751 - root - INFO - Environmental variable FME_VALID_DIR=/pscratch/sd/b/bhenn/data/2023-11-01-subset-vertically-resolved-1deg-fme-amip-ensemble-dataset/validation/ic_0002.
2024-05-06 07:29:29,751 - root - INFO - Environmental variable FME_STATS_DIR=/pscratch/sd/b/bhenn/data/2023-11-01-vertically-resolved-1deg-fme-amip-ensemble-dataset-stats/residual.
2024-05-06 07:29:29,751 - root - WARNING - Environmental variable FME_CHECKPOINT_DIR not found.
2024-05-06 07:29:29,751 - root - INFO - Environmental variable FME_OUTPUT_DIR=/pscratch/sd/b/bhenn/fme-output/25244315.
2024-05-06 07:29:29,751 - root - INFO - Environmental variable FME_IMAGE=fme:ff6ac271.
2024-05-06 07:29:29,751 - root - INFO - --------------- Versions ---------------
2024-05-06 07:29:29,751 - root - INFO - Torch: 2.1.0a0+29c30b1
2024-05-06 07:29:29,752 - root - INFO - ----------------------------------------
2024-05-06 07:29:29,752 - root - WARNING - Beaker Experiment ID not found.
wandb: Currently logged in as: bhenn1983 (ai2cm). Use `wandb login --relogin` to force relogin
wandb: wandb version 0.16.6 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.15.0
wandb: Run data is saved locally in /output/wandb/run-20240506_072931-yqt9h2uv
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run test-train-weighted-best-inference
wandb: ⭐️ View project at https://wandb.ai/ai2cm/fourcastnet
wandb: 🚀 View run at https://wandb.ai/ai2cm/fourcastnet/runs/yqt9h2uv
2024-05-06 07:29:31,892 - root - INFO - rank 0, begin data loader init
2024-05-06 07:29:31,894 - root - INFO - Opening data at /traindata/ic_0001/*.nc
2024-05-06 07:29:32,746 - root - INFO - Found 1459 samples.
2024-05-06 07:29:32,747 - root - INFO - Image shape is 180 x 360.
2024-05-06 07:29:32,747 - root - INFO - Following variables are available: ['DLWRFsfc', 'DSWRFsfc', 'DSWRFtoa', 'GRAUPELsfc', 'HGTsfc', 'ICEsfc', 'LHTFLsfc', 'PRATEsfc', 'PRESsfc', 'SHTFLsfc', 'SNOWsfc', 'ULWRFsfc', 'ULWRFtoa', 'USWRFsfc', 'USWRFtoa', 'air_temperature_0', 'air_temperature_1', 'air_temperature_2', 'air_temperature_3', 'air_temperature_4', 'air_temperature_5', 'air_temperature_6', 'air_temperature_7', 'ak_0', 'ak_1', 'ak_2', 'ak_3', 'ak_4', 'ak_5', 'ak_6', 'ak_7', 'ak_8', 'bk_0', 'bk_1', 'bk_2', 'bk_3', 'bk_4', 'bk_5', 'bk_6', 'bk_7', 'bk_8', 'eastward_wind_0', 'eastward_wind_1', 'eastward_wind_2', 'eastward_wind_3', 'eastward_wind_4', 'eastward_wind_5', 'eastward_wind_6', 'eastward_wind_7', 'grid_xt', 'grid_yt', 'land_fraction', 'northward_wind_0', 'northward_wind_1', 'northward_wind_2', 'northward_wind_3', 'northward_wind_4', 'northward_wind_5', 'northward_wind_6', 'northward_wind_7', 'ocean_fraction', 'sea_ice_fraction', 'soil_moisture', 'specific_total_water_0', 'specific_total_water_1', 'specific_total_water_2', 'specific_total_water_3', 'specific_total_water_4', 'specific_total_water_5', 'specific_total_water_6', 'specific_total_water_7', 'surface_temperature', 'tendency_of_total_water_path', 'tendency_of_total_water_path_due_to_advection', 'time', 'total_water_path'].
2024-05-06 07:29:33,100 - root - INFO - Subsetting dataset samples according to slice(None, None, 16).
2024-05-06 07:29:33,102 - root - INFO - Opening data at /validdata/*.nc
2024-05-06 07:29:33,899 - root - INFO - Found 1459 samples.
2024-05-06 07:29:33,900 - root - INFO - Image shape is 180 x 360.
2024-05-06 07:29:33,900 - root - INFO - Following variables are available: ['DLWRFsfc', 'DSWRFsfc', 'DSWRFtoa', 'GRAUPELsfc', 'HGTsfc', 'ICEsfc', 'LHTFLsfc', 'PRATEsfc', 'PRESsfc', 'SHTFLsfc', 'SNOWsfc', 'ULWRFsfc', 'ULWRFtoa', 'USWRFsfc', 'USWRFtoa', 'air_temperature_0', 'air_temperature_1', 'air_temperature_2', 'air_temperature_3', 'air_temperature_4', 'air_temperature_5', 'air_temperature_6', 'air_temperature_7', 'ak_0', 'ak_1', 'ak_2', 'ak_3', 'ak_4', 'ak_5', 'ak_6', 'ak_7', 'ak_8', 'bk_0', 'bk_1', 'bk_2', 'bk_3', 'bk_4', 'bk_5', 'bk_6', 'bk_7', 'bk_8', 'eastward_wind_0', 'eastward_wind_1', 'eastward_wind_2', 'eastward_wind_3', 'eastward_wind_4', 'eastward_wind_5', 'eastward_wind_6', 'eastward_wind_7', 'grid_xt', 'grid_yt', 'land_fraction', 'northward_wind_0', 'northward_wind_1', 'northward_wind_2', 'northward_wind_3', 'northward_wind_4', 'northward_wind_5', 'northward_wind_6', 'northward_wind_7', 'ocean_fraction', 'sea_ice_fraction', 'soil_moisture', 'specific_total_water_0', 'specific_total_water_1', 'specific_total_water_2', 'specific_total_water_3', 'specific_total_water_4', 'specific_total_water_5', 'specific_total_water_6', 'specific_total_water_7', 'surface_temperature', 'tendency_of_total_water_path', 'tendency_of_total_water_path_due_to_advection', 'time', 'total_water_path'].
2024-05-06 07:29:33,933 - root - INFO - Subsetting dataset samples according to slice(None, None, 16).
2024-05-06 07:29:33,934 - root - INFO - rank 0, data loader initialized
2024-05-06 07:29:33,934 - root - INFO - train data: 92 samples, 46 batches
2024-05-06 07:29:35,005 - root - INFO - train data: first sample's initial time: 1990-01-01 00:00:00
2024-05-06 07:29:35,005 - root - INFO - train data: last sample's initial time: 1990-12-31 00:00:00
2024-05-06 07:29:35,006 - root - INFO - valid data: 92 samples, 46 batches
2024-05-06 07:29:36,175 - root - INFO - valid data: first sample's initial time: 1990-01-01 00:00:00
2024-05-06 07:29:36,176 - root - INFO - valid data: last sample's initial time: 1990-12-31 00:00:00
2024-05-06 07:29:40,979 - root - INFO - Starting model initialization
[1714980582.572284] [92c90024c028:157  :0]           debug.c:1294 UCX  WARN  ucs_debug_disable_signal: signal 1 was not set in ucs
[1714980582.572324] [92c90024c028:157  :1]           debug.c:1294 UCX  WARN  ucs_debug_disable_signal: signal 11 was not set in ucs
[1714980582.572334] [92c90024c028:157  :0]        spinlock.c:29   UCX  WARN  ucs_recursive_spinlock_destroy() failed: busy
[1714980582.572354] [92c90024c028:157  :1]        spinlock.c:29   UCX  WARN  ucs_recursive_spinlock_destroy() failed: busy
[1714980582.572353] [92c90024c028:157  :2]           debug.c:1294 UCX  WARN  ucs_debug_disable_signal: signal 11 was not set in ucs
[1714980582.572409] [92c90024c028:157  :2]        spinlock.c:29   UCX  WARN  ucs_recursive_spinlock_destroy() failed: busy
[92c90024c028:157  :0:412] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
[92c90024c028:157  :1:436] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
[92c90024c028:157  :2:414] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
[92c90024c028:157  :3:393] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
[1714980582.572404] [92c90024c028:157  :3]           debug.c:1294 UCX  WARN  ucs_debug_disable_signal: signal 11 was not set in ucs
[1714980582.572436] [92c90024c028:157  :3]        spinlock.c:29   UCX  WARN  ucs_recursive_spinlock_destroy() failed: busy
[1714980582.572433] [92c90024c028:157  :4]           debug.c:1294 UCX  WARN  ucs_debug_disable_signal: signal 11 was not set in ucs
[1714980582.572460] [92c90024c028:157  :5]           debug.c:1294 UCX  WARN  ucs_debug_disable_signal: signal 11 was not set in ucs
[1714980582.572469] [92c90024c028:157  :4]        spinlock.c:29   UCX  WARN  ucs_recursive_spinlock_destroy() failed: busy
[1714980582.572490] [92c90024c028:157  :5]        spinlock.c:29   UCX  WARN  ucs_recursive_spinlock_destroy() failed: busy
[1714980582.572490] [92c90024c028:157  :6]           debug.c:1294 UCX  WARN  ucs_debug_disable_signal: signal 11 was not set in ucs
[92c90024c028:157  :4:419] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
[92c90024c028:157  :5:404] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
[92c90024c028:157  :6:397] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
==== backtrace (tid:    414) ====
 0 0x0000000000042520 __sigaction()  ???:0
=================================
[2024-05-06 07:29:45,438] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: -11) local_rank: 0 (pid: 157) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.1.0a0+29c30b1', 'console_scripts', 'torchrun')())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 797, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 788, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=====================================================
/full-model/fme/fme/ace/train.py FAILED
-----------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
-----------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-05-06_07:29:45
  host      : 92c90024c028
  rank      : 0 (local_rank: 0)
  exitcode  : -11 (pid: 157)
  error_file: <N/A>
  traceback : Signal 11 (SIGSEGV) received by PID 157
=====================================================
```

**Comment by brianhenn** [comment]
Turns out the jobs that segfaulted were invoked with `torchrun --nproc_per_node 1 ...`, which is not a normal configuration and puts our `Distributed` object into a bit of an ambiguous state. Apparently it also causes the segfault? When `torchrun` with the correct >1 GPUs, the segfault went away for these images (and so is still not currently observed/reproducible on any  image since the 23.08 upgrade).

**Comment by brianhenn** [comment]
Closing this because it was likely a false alarm, see comment above.
