### ISSUE TITLE
Perlmutter training jobs hanging on NCCL timeout

### ISSUE THREAD

**Issue by brianhenn** [ai2cm/ace#348]
Two recent jobs died with the same error, both at the end of the `train_one_epoch` step (though not for the first epoch). These were running on 4 GPUs on a Perlmutter node in the regular queue, using image from [this commit](https://github.com/ai2cm/full-model/pull/800/commits/3fdce583ace643aee9223433a7410a5a3a2bdd9d). Other jobs from same commit have made it past this point.
```
2024-05-07 15:51:09,140 - root - INFO - Starting training step on epoch 3
[E ProcessGroupNCCL.cpp:457] [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1132079, OpType=ALLREDUCE, NumelIn=304640, NumelOut=304640, Timeout(ms)=1800000) ran for 1800035 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:457] [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1132079, OpType=ALLREDUCE, NumelIn=304640, NumelOut=304640, Timeout(ms)=1800000) ran for 1800558 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:457] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1132079, OpType=ALLREDUCE, NumelIn=304640, NumelOut=304640, Timeout(ms)=1800000) ran for 1800946 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:471] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:477] To avoid data inconsistency, we are taking the entire process down.
[E ProcessGroupNCCL.cpp:842] [Rank 3] NCCL watchdog thread terminated with exception: [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1132079, OpType=ALLREDUCE, NumelIn=304640, NumelOut=304640, Timeout(ms)=1800000) ran for 1800035 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:471] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:477] To avoid data inconsistency, we are taking the entire process down.
[E ProcessGroupNCCL.cpp:842] [Rank 2] NCCL watchdog thread terminated with exception: [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1132079, OpType=ALLREDUCE, NumelIn=304640, NumelOut=304640, Timeout(ms)=1800000) ran for 1800558 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:471] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:477] To avoid data inconsistency, we are taking the entire process down.
[E ProcessGroupNCCL.cpp:842] [Rank 1] NCCL watchdog thread terminated with exception: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1132079, OpType=ALLREDUCE, NumelIn=304640, NumelOut=304640, Timeout(ms)=1800000) ran for 1800946 milliseconds before timing out.
terminate called after throwing an instance of 'terminate called after throwing an instance of 'std::runtime_errorstd::runtime_error'
'
terminate called after throwing an instance of 'std::runtime_error'
  what():    what():  [Rank 1] NCCL watchdog thread terminated with exception: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1132079, OpType=ALLREDUCE, NumelIn=304640, NumelOut=304640, Timeout(ms)=1800000) ran for 1800946 milliseconds before timing out.[Rank 3] NCCL watchdog thread terminated with exception: [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1132079, OpType=ALLREDUCE, NumelIn=304640, NumelOut=304640, Timeout(ms)=1800000) ran for 1800035 milliseconds before timing out.

  what():  [Rank 2] NCCL watchdog thread terminated with exception: [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1132079, OpType=ALLREDUCE, NumelIn=304640, NumelOut=304640, Timeout(ms)=1800000) ran for 1800558 milliseconds before timing out.
[2024-05-07 19:22:57,065] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 163 closing signal SIGTERM
[2024-05-07 19:22:57,229] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: -6) local_rank: 1 (pid: 164) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.1.0a0+29c30b1', 'console_scripts', 'torchrun')())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 797, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 788, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
====================================================
/full-model/fme/fme/ace/train.py FAILED
----------------------------------------------------
Failures:
[1]:
  time      : 2024-05-07_19:22:57
  host      : 8ac5f280cea6
  rank      : 2 (local_rank: 2)
  exitcode  : -6 (pid: 165)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 165
[2]:
  time      : 2024-05-07_19:22:57
  host      : 8ac5f280cea6
  rank      : 3 (local_rank: 3)
  exitcode  : -6 (pid: 166)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 166
----------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-05-07_19:22:57
  host      : 8ac5f280cea6
  rank      : 1 (local_rank: 1)
  exitcode  : -6 (pid: 164)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 164
====================================================
```

**Comment by brianhenn** [comment]
Here's another one, this time on the validation step. Of order ~100 recent training/val/inference epochs with 1deg AMIP on Perlmutter, 3 of these types of failures have occurred.
```
2024-05-09 16:45:05,824 - root - INFO - Starting validation step on epoch 11
[E ProcessGroupNCCL.cpp:457] [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=395114, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=1800000) ran for 1800523 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:471] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:477] To avoid data inconsistency, we are taking the entire process down.
[E ProcessGroupNCCL.cpp:842] [Rank 2] NCCL watchdog thread terminated with exception: [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=395114, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=1800000) ran for 1800523 milliseconds before timing out.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 2] NCCL watchdog thread terminated with exception: [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=395114, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=1800000) ran for 1800523 milliseconds before timing out.
[2024-05-09 17:46:21,783] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 163 closing signal SIGTERM
[2024-05-09 17:46:21,783] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 164 closing signal SIGTERM
[2024-05-09 17:46:21,783] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 166 closing signal SIGTERM
[2024-05-09 17:46:22,312] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: -6) local_rank: 2 (pid: 165) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.1.0a0+29c30b1', 'console_scripts', 'torchrun')())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 797, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 788, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
====================================================
/full-model/fme/fme/ace/train.py FAILED
----------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
----------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-05-09_17:46:21
  host      : d7a0fe38db1a
  rank      : 2 (local_rank: 2)
  exitcode  : -6 (pid: 165)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 165
====================================================
```

**Comment by brianhenn** [comment]
Have had an extended conversation with Peter Harrington at NERSC about possible ways to avoid this (INC0219806). It's plausible this is due to too many i/o reads of the dataset when running multiple jobs and workers simultaneously, and some suggestions were posted in that thread. But in the meantime this error only occurred 4 times in a couple hundred collective epochs of training, so fixing it seems like not the highest priority.

**Comment by brianhenn** [comment]
This hasn't come up much recently so I'm closing as perhaps a result of running too many jobs reading the same pscratch data. Can reopen if need be.
