### ISSUE TITLE
Error loading older model for standalone inference 

### ISSUE THREAD

**Issue by AnnaKwa** [ai2cm/ace#350]
I ran into this error starting an inference run in a recent image using an older trained model (trained a couple months ago in March 2024):
```
2024-05-09T16:59:19.092676580Z 2024-05-09 16:59:19,092 - root - INFO - Loading trained model checkpoint from /trained_model/training_checkpoints/best_inference_ckpt.tar
2024-05-09T16:59:23.777932478Z Traceback (most recent call last):
2024-05-09T16:59:23.778608766Z   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2024-05-09T16:59:23.778671286Z     return _run_code(code, main_globals, None,
2024-05-09T16:59:23.778892335Z   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
2024-05-09T16:59:23.778914515Z     exec(code, run_globals)
2024-05-09T16:59:23.779258514Z   File "/full-model/fme/fme/ace/inference/__main__.py", line 8, in <module>
2024-05-09T16:59:23.779282694Z     main(yaml_config=args.yaml_config)
2024-05-09T16:59:23.779501603Z   File "/full-model/fme/fme/ace/inference/inference.py", line 216, in main
2024-05-09T16:59:23.779523193Z     stepper = config.load_stepper(
2024-05-09T16:59:23.779764652Z   File "/full-model/fme/fme/ace/inference/inference.py", line 150, in load_stepper
2024-05-09T16:59:23.779788692Z     stepper = _load_stepper(
2024-05-09T16:59:23.780039211Z   File "/full-model/fme/fme/ace/inference/inference.py", line 41, in _load_stepper
2024-05-09T16:59:23.780060661Z     stepper = SingleModuleStepper.from_state(
2024-05-09T16:59:23.780320790Z   File "/full-model/fme/fme/core/stepper.py", line 579, in from_state
2024-05-09T16:59:23.780338540Z     stepper.load_state(state)
2024-05-09T16:59:23.780599639Z   File "/full-model/fme/fme/core/stepper.py", line 534, in load_state
2024-05-09T16:59:23.780651179Z     self.module.load_state_dict(state["module"])
2024-05-09T16:59:23.780862479Z   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 2091, in load_state_dict
2024-05-09T16:59:23.780882669Z     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
2024-05-09T16:59:23.781138198Z RuntimeError: Error(s) in loading state_dict for DummyWrapper:
2024-05-09T16:59:23.781160458Z 	Unexpected key(s) in state_dict: "module.device_buffer". 
```
Beaker link: [2024-05-09-amip-8level-4deg-inference-seed0](https://beaker.org/ex/01HXF49BVWZ3PMS8WSYHCPBHNX)

Testing interactively, this older model seems to work for inference until [this commit to main](https://github.com/ai2cm/full-model/commit/56cfae762fcb0592b290cdd11f67dc9917aff5c3). Models trained more recently don't seem to have this issue.

**Comment by oliverwm1** [comment]
Thanks for reporting. We should definitely fix this. @mcgibbon any ideas?

**Comment by mcgibbon** [comment]
This should be very fixable. device_buffer is some kind of special tensor used for transferring data to/from device, and doesn't need to be saved or loaded, so we should be able to ignore this error.

It sounds like when we vendorized ai2modulus, that change removed this device_buffer tensor from the model, and we'll need to ignore its values in previous checkpoints.
