### ISSUE TITLE
Standalone inference fails with stepper that uses `residual_normalization`

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#373]
I tried running standalone inference with a model that was trained using the `residual_normalization` feature. It failed with complaints about not finding the appropriate scaling netCDF. The stepper should not require this netCDF for inference—it should be serializing the necessary scaling values along with the model.

Traceback:
```
2024-06-20T20:53:49.682568809Z 2024-06-20 20:53:49,682 - root - INFO - Loading trained model checkpoint from /trained_model/best_ckpt.tar
2024-06-20T20:53:56.028652583Z Traceback (most recent call last):
2024-06-20T20:53:56.029058091Z   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2024-06-20T20:53:56.029061688Z     return _run_code(code, main_globals, None,
2024-06-20T20:53:56.029258033Z   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
2024-06-20T20:53:56.029259766Z     exec(code, run_globals)
2024-06-20T20:53:56.029428551Z   File "/full-model/fme/fme/ace/inference/evaluator.py", line 297, in <module>
2024-06-20T20:53:56.029430616Z     main(
2024-06-20T20:53:56.029610052Z   File "/full-model/fme/fme/ace/inference/evaluator.py", line 208, in main
2024-06-20T20:53:56.029612042Z     stepper = config.load_stepper(
2024-06-20T20:53:56.029784112Z   File "/full-model/fme/fme/ace/inference/evaluator.py", line 145, in load_stepper
2024-06-20T20:53:56.029786125Z     stepper = _load_stepper(
2024-06-20T20:53:56.029957231Z   File "/full-model/fme/fme/ace/inference/evaluator.py", line 41, in _load_stepper
2024-06-20T20:53:56.029958696Z     stepper = SingleModuleStepper.from_state(
2024-06-20T20:53:56.030128605Z   File "/full-model/fme/fme/core/stepper.py", line 631, in from_state
2024-06-20T20:53:56.030138602Z     stepper = cls(
2024-06-20T20:53:56.030317426Z   File "/full-model/fme/fme/core/stepper.py", line 379, in __init__
2024-06-20T20:53:56.030335113Z     residual_normalizer=config.residual_normalization.build(
2024-06-20T20:53:56.030475348Z   File "/full-model/fme/fme/core/normalizer.py", line 58, in build
2024-06-20T20:53:56.030481594Z     return get_normalizer(
2024-06-20T20:53:56.030647434Z   File "/full-model/fme/fme/core/normalizer.py", line 153, in get_normalizer
2024-06-20T20:53:56.030652851Z     means = load_dict_from_netcdf(
2024-06-20T20:53:56.030820356Z   File "/full-model/fme/fme/core/normalizer.py", line 176, in load_dict_from_netcdf
2024-06-20T20:53:56.030825472Z     ds = netCDF4.Dataset(path)
2024-06-20T20:53:56.030987635Z   File "src/netCDF4/_netCDF4.pyx", line 2469, in netCDF4._netCDF4.Dataset.__init__
2024-06-20T20:53:56.031151718Z   File "src/netCDF4/_netCDF4.pyx", line 2028, in netCDF4._netCDF4._ensure_nc_success
2024-06-20T20:53:56.031322550Z FileNotFoundError: [Errno 2] No such file or directory: '/statsdata/centering.nc'
```
beaker job: https://beaker.org/ex/01J0VNRF8QKFAB4C263C473RPG/tasks/01J0VNRF8WDHSDEFQPWM78K7X5/job/01J0VPFZMYP4ADGTWMV6DGACP4

**Comment by oliverwm1** [comment]
Resolved by ai2cm/full-model#921
