### ISSUE TITLE
Training job dies on jupiter-weka with apparent dataset read error

### ISSUE THREAD

**Issue by brianhenn** [ai2cm/ace#414]
A few recent training jobs ([eg](https://beaker.org/ex/01J4J7N372H71244CE1C25T94D/tasks/01J4J7N378KWP30Y5VHF0MD9Z7/job/01J4QCABRFVWGVEJZ69N1K0JF6)) have died on jupiter with the following apparent data read error upon initializing the data loaders off of datasets stored on weka. If the job is restarted, it generally then runs fine, indicating a transient I/O error. Not sure how to avoid.
```
2024-08-07T22:57:28.933825600Z 2024-08-07 22:57:28,933 - root - INFO - Opening data at /climate-default/2024-07-24-vertically-resolved-c96-1deg-shield-amip-ensemble-dataset/netCDFs/ic_0001/*.nc
2024-08-07T22:58:24.992432888Z Traceback (most recent call last):
2024-08-07T22:58:24.992473811Z   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2024-08-07T22:58:24.992476547Z     return _run_code(code, main_globals, None,
2024-08-07T22:58:24.992478091Z   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
2024-08-07T22:58:24.992480045Z     exec(code, run_globals)
2024-08-07T22:58:24.992481471Z   File "/full-model/fme/fme/ace/train/__main__.py", line 11, in <module>
2024-08-07T22:58:24.992483234Z     main(yaml_config=args.yaml_config)
2024-08-07T22:58:24.992484701Z   File "/full-model/fme/fme/ace/train/train.py", line 545, in main
2024-08-07T22:58:24.992486177Z     run_train_from_config(train_config)
2024-08-07T22:58:24.992487339Z   File "/full-model/fme/fme/ace/train/train.py", line 528, in run_train_from_config
2024-08-07T22:58:24.992488764Z     trainer = Trainer(config)
2024-08-07T22:58:24.992489872Z   File "/full-model/fme/fme/ace/train/train.py", line 111, in __init__
2024-08-07T22:58:24.992491251Z     self.train_data = get_data_loader(
2024-08-07T22:58:24.992492386Z   File "/full-model/fme/fme/core/data_loading/getters.py", line 100, in get_data_loader
2024-08-07T22:58:24.992493984Z     dataset = get_dataset(config.dataset, requirements, strict=config.strict_ensemble)
2024-08-07T22:58:24.992495300Z   File "/full-model/fme/fme/core/data_loading/getters.py", line 53, in get_dataset
2024-08-07T22:58:24.992496917Z     datasets = get_datasets(dataset_configs, requirements)
2024-08-07T22:58:24.992498093Z   File "/full-model/fme/fme/core/data_loading/getters.py", line 41, in get_datasets
2024-08-07T22:58:24.992499491Z     dataset = XarrayDataset(config, requirements)
2024-08-07T22:58:24.992500655Z   File "/full-model/fme/fme/core/data_loading/_xarray.py", line 305, in __init__
2024-08-07T22:58:24.992502200Z     self._get_files_stats(config.n_repeats, config.infer_timestep)
2024-08-07T22:58:24.992503472Z   File "/full-model/fme/fme/core/data_loading/_xarray.py", line 397, in _get_files_stats
2024-08-07T22:58:24.992504776Z     logging.info(f"Image shape is {img_shape[0]} x {img_shape[1]}.")
2024-08-07T21:49:11.974231764Z IndexError: tuple index out of range
```

**Comment by brianhenn** [comment]
I think this may be due to the `global_mean_co2` scalar feature being incompatible with [the code that reports the image shape](https://github.com/ai2cm/full-model/blob/6517851a23fce52f723a4ee1c860492d015ac809/fme/fme/core/data_loading/_xarray.py#L387-L398), it if happens that this variable is the first one grabbed in the loop. 

A [few](https://beaker.org/ex/01J4BCWTFM97VVFFQZ23A3FMBS/tasks/01J4BCWTFTPDNJG3274Q6ASRTS/job/01J4QJKE4GVXSGMR8PECE80P53) [more](https://beaker.org/ex/01J4BCWXM69S20KENAWMF888FJ/tasks/01J4BCWXMDGFPRRWGKME3TX87X/job/01J4QJ05B3S10Y9GF58MMA7JQS) [jobs](https://beaker.org/ex/01J4J7N6CJ73P5PJEAQYK7N1SB/tasks/01J4J7N6CQCZ09DQFDRXYB72JF/job/01J4QN1TC6D021H11GY4ECYKEG) have failed this way; will attempt a fix.

**Comment by oliverwm1** [comment]
Yes, I think this is similar to https://github.com/ai2cm/ace/issues/241. Probably should just use the `horizontal_coordinates` property for logging instead of having this additional custom code to try and infer the shape.
