### ISSUE TITLE
Intermittent img_shape error

### ISSUE THREAD

**Issue by mcgibbon** [ai2cm/ace#420]
I've been getting `IndexError: tuple index out of range` as an _intermittent_ error on `logging.info(f"Image shape is {img_shape[0]} x {img_shape[1]}.")` in my jobs, which is very strange:

```
2024-08-12T22:11:17.480352948Z wandb: Currently logged in as: oliverwm (ai2cm). Use `wandb login --relogin` to force relogin
2024-08-12T22:11:23.070171828Z wandb: Tracking run with wandb version 0.17.6
2024-08-12T22:11:23.070184833Z wandb: Run data is saved locally in /output/wandb/run-20240812_221117-zxoag2y3
2024-08-12T22:11:23.070186659Z wandb: Run `wandb offline` to turn off syncing.
2024-08-12T22:11:23.071662494Z wandb: Resuming run 2024-08-12-shield-amip-c96-v3-acev2-1mem-rs0
2024-08-12T22:11:23.071683324Z wandb: ⭐️ View project at https://wandb.ai/ai2cm/ace
2024-08-12T22:11:23.071720473Z wandb: 🚀 View run at https://wandb.ai/ai2cm/ace/runs/zxoag2y3
2024-08-12T22:11:23.294551785Z 2024-08-12 22:11:23,294 - root - INFO - Current device is cuda:0
2024-08-12T22:11:23.294818462Z 2024-08-12 22:11:23,294 - root - INFO - rank 0, begin data loader init
2024-08-12T22:11:23.311354031Z 2024-08-12 22:11:23,311 - root - INFO - Opening data at /climate-default/2024-07-24-vertically-resolved-c96-4deg-shield-amip-ensemble-dataset/netCDFs/ic_0001/*.nc
2024-08-12T22:12:20.052671242Z Traceback (most recent call last):
2024-08-12T22:12:20.052697407Z   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2024-08-12T22:12:20.052699863Z     return _run_code(code, main_globals, None,
2024-08-12T22:12:20.052701648Z   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
2024-08-12T22:12:20.052703460Z     exec(code, run_globals)
2024-08-12T22:12:20.052705084Z   File "/full-model/fme/fme/ace/train/__main__.py", line 11, in <module>
2024-08-12T22:12:20.052706886Z     main(yaml_config=args.yaml_config)
2024-08-12T22:12:20.052708273Z   File "/full-model/fme/fme/ace/train/train.py", line 545, in main
2024-08-12T22:12:20.052710043Z     run_train_from_config(train_config)
2024-08-12T22:12:20.052711791Z   File "/full-model/fme/fme/ace/train/train.py", line 528, in run_train_from_config
2024-08-12T22:12:20.052713226Z     trainer = Trainer(config)
2024-08-12T22:12:20.052714598Z   File "/full-model/fme/fme/ace/train/train.py", line 111, in __init__
2024-08-12T22:12:20.052715817Z     self.train_data = get_data_loader(
2024-08-12T22:12:20.052717459Z   File "/full-model/fme/fme/core/data_loading/getters.py", line 100, in get_data_loader
2024-08-12T22:12:20.052719242Z     dataset = get_dataset(config.dataset, requirements, strict=config.strict_ensemble)
2024-08-12T22:12:20.052720681Z   File "/full-model/fme/fme/core/data_loading/getters.py", line 53, in get_dataset
2024-08-12T22:12:20.052722107Z     datasets = get_datasets(dataset_configs, requirements)
2024-08-12T22:12:20.052723894Z   File "/full-model/fme/fme/core/data_loading/getters.py", line 41, in get_datasets
2024-08-12T22:12:20.052725175Z     dataset = XarrayDataset(config, requirements)
2024-08-12T22:12:20.052726558Z   File "/full-model/fme/fme/core/data_loading/_xarray.py", line 305, in __init__
2024-08-12T22:12:20.052727828Z     self._get_files_stats(config.n_repeats, config.infer_timestep)
2024-08-12T22:12:20.052729256Z   File "/full-model/fme/fme/core/data_loading/_xarray.py", line 397, in _get_files_stats
2024-08-12T22:12:20.052730547Z     logging.info(f"Image shape is {img_shape[0]} x {img_shape[1]}.")
2024-08-12T22:12:20.052731857Z IndexError: tuple index out of range
```

[Logs with error](https://beaker.org/api/v3/jobs/01J54A54XVQ2XK849WMFD4WMMB/logs?tail=2), [logs on identically configured job without error](https://beaker.org/api/v3/jobs/01J556MXC8HNJ81QW9CYW8950K/logs?tail=2). These links may not work as expected as I'm going to re-submit the [job that had the error](https://beaker.org/ex/01J543BNY6E6MGHBY38WDDRWZ9/tasks/01J543BNYE01CMYD3EK0JK1MY5/job/01J548BMP2XB4GBQN90HP4CFCG) (link to [job without error](https://beaker.org/ex/01J543BK6PV6CM1PNWTYQ7P955/tasks/01J543BK6ZQ8ETKHPG4BSTYNR5/job/01J556MXC8HNJ81QW9CYW8950K)).

**Comment by mcgibbon** [comment]
Duplicate of ai2cm/ace#414
