### ISSUE TITLE
Paneled data plotting errors with HEALPix input

### ISSUE THREAD

**Issue by AnnaKwa** [ai2cm/ace#436]
Some of the plotting code still assumes the spatial dims are the last two.

Beaker [job](https://beaker.org/ex/01J5Y7CRC7380GSGK5ZJ6RR0MK/tasks/01J5Y7CRCE3NAVAATTE3D6FYER/job/01J5Y7CRHW2MGXQJYEPETMEPD2) and [logs](https://beaker.org/api/v3/jobs/01J5Y7CRHW2MGXQJYEPETMEPD2/logs?tail=2)
```
2024-08-23T04:50:20.082983810Z Traceback (most recent call last):
2024-08-23T04:50:20.083188130Z   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2024-08-23T04:50:20.083199703Z     return _run_code(code, main_globals, None,
2024-08-23T04:50:20.083364844Z   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
2024-08-23T04:50:20.083394026Z     exec(code, run_globals)
2024-08-23T04:50:20.083530096Z   File "/full-model/fme/fme/ace/train/__main__.py", line 11, in <module>
2024-08-23T04:50:20.083534751Z     main(yaml_config=args.yaml_config)
2024-08-23T04:50:20.083698582Z   File "/full-model/fme/fme/ace/train/train.py", line 554, in main
2024-08-23T04:50:20.083701320Z     run_train_from_config(train_config)
2024-08-23T04:50:20.083869439Z   File "/full-model/fme/fme/ace/train/train.py", line 538, in run_train_from_config
2024-08-23T04:50:20.083871892Z     trainer.train()
2024-08-23T04:50:20.084044086Z   File "/full-model/fme/fme/ace/train/train.py", line 223, in train
2024-08-23T04:50:20.084046236Z     inference_logs = self.inference_one_epoch()
2024-08-23T04:50:20.084214702Z   File "/full-model/fme/fme/ace/train/train.py", line 420, in inference_one_epoch
2024-08-23T04:50:20.084216923Z     logs = aggregator.get_logs(label="inference")
2024-08-23T04:50:20.084385953Z   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2024-08-23T04:50:20.084388197Z     return func(*args, **kwargs)
2024-08-23T04:50:20.084558916Z   File "/full-model/fme/fme/core/aggregator/inference/main.py", line 363, in get_logs
2024-08-23T04:50:20.084561029Z     logs.update(time_dependent_aggregator.get_logs(label=name))
2024-08-23T04:50:20.084730989Z   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2024-08-23T04:50:20.084733114Z     return func(*args, **kwargs)
2024-08-23T04:50:20.084904821Z   File "/full-model/fme/fme/core/aggregator/inference/enso/enso.py", line 265, in get_logs
2024-08-23T04:50:20.084906633Z     coefficient_map = plot_paneled_data(
2024-08-23T04:50:20.085075313Z   File "/full-model/fme/fme/core/aggregator/plotting.py", line 120, in plot_paneled_data
2024-08-23T04:50:20.085077491Z     all_data = _stitch_data_panels(data, vmin=vmin)
2024-08-23T04:50:20.085245143Z   File "/full-model/fme/fme/core/aggregator/plotting.py", line 163, in _stitch_data_panels
2024-08-23T04:50:20.085247286Z     stitched_data[start_row:end_row, start_col:end_col] = arr
2024-08-23T04:50:20.085424207Z ValueError: could not broadcast input array from shape (12,64,64) into shape (12,64)
```

**Comment by AnnaKwa** [comment]
Not sure what commit the beaker job used, but I ran inference with a HEALPix model interactively on the current main and it succeeded without hitting this error.
