### ISSUE TITLE
Inference runs with an overriding data ocean still attempt to load slab ocean forcing variables

### ISSUE THREAD

**Issue by spencerkclark** [ai2cm/ace#465]
When trying to run an AMIP-style experiment with a model trained using a slab ocean via the ocean-override capability, I encountered an error indicating that ACE was still looking for the forcing variables needed for the slab ocean (see [this Beaker experiment](https://beaker.org/ex/01J9250BNAKZMR9D9MYG1GRZ4D/tasks/01J9250BNJQ85MYH1B6Z5QCE2K/job/01J92E3B0M36BF2585N6YMM1F0)):

```
2024-09-30T22:49:17.346892858Z 2024-09-30 22:49:17,346 - root - INFO - --------------- Versions ---------------
2024-09-30T22:49:17.347209839Z 2024-09-30 22:49:17,347 - root - INFO - Torch: 2.1.0a0+29c30b1
2024-09-30T22:49:17.347365990Z 2024-09-30 22:49:17,347 - root - INFO - ----------------------------------------
2024-09-30T22:49:17.464128408Z 2024-09-30 22:49:17,463 - root - INFO - Current device is cuda:0
2024-09-30T22:49:17.464544009Z 2024-09-30 22:49:17,464 - root - INFO - Loading trained model checkpoint from /ckpt.tar
2024-09-30T22:49:22.898118651Z 2024-09-30 22:49:22,897 - root - INFO - Loading inference data
2024-09-30T22:49:22.932433668Z 2024-09-30 22:49:22,932 - root - INFO - Opening data at /climate-default/2024-07-24-vertically-resolved-c96-1deg-shield-amip-ensemble-dataset/netCDFs/ic_0002/*.nc
2024-09-30T22:51:01.477814624Z Traceback (most recent call last):
2024-09-30T22:51:01.478280413Z   File "/usr/local/lib/python3.10/dist-packages/xarray/core/dataset.py", line 1477, in _construct_dataarray
2024-09-30T22:51:01.478286758Z     variable = self._variables[name]
2024-09-30T22:51:01.478517443Z KeyError: 'prescribed_qflux'
2024-09-30T22:51:01.478712920Z 
2024-09-30T22:51:01.478718860Z During handling of the above exception, another exception occurred:
2024-09-30T22:51:01.478721285Z 
2024-09-30T22:51:01.478912910Z Traceback (most recent call last):
2024-09-30T22:51:01.479133185Z   File "/usr/local/lib/python3.10/dist-packages/xarray/core/dataset.py", line 1576, in __getitem__
2024-09-30T22:51:01.479136392Z     return self._construct_dataarray(key)
2024-09-30T22:51:01.479336312Z   File "/usr/local/lib/python3.10/dist-packages/xarray/core/dataset.py", line 1479, in _construct_dataarray
2024-09-30T22:51:01.479339108Z     _, name, variable = _get_virtual_variable(self._variables, name, self.sizes)
2024-09-30T22:51:01.479536360Z   File "/usr/local/lib/python3.10/dist-packages/xarray/core/dataset.py", line 213, in _get_virtual_variable
2024-09-30T22:51:01.479539836Z     raise KeyError(key)
2024-09-30T22:51:01.479741193Z KeyError: 'prescribed_qflux'
2024-09-30T22:51:01.479943875Z 
2024-09-30T22:51:01.479946258Z The above exception was the direct cause of the following exception:
2024-09-30T22:51:01.479948401Z 
2024-09-30T22:51:01.480160595Z Traceback (most recent call last):
2024-09-30T22:51:01.480386422Z   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2024-09-30T22:51:01.480389623Z     return _run_code(code, main_globals, None,
2024-09-30T22:51:01.480592009Z   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
2024-09-30T22:51:01.480594854Z     exec(code, run_globals)
2024-09-30T22:51:01.480792545Z   File "/full-model/fme/fme/ace/evaluator.py", line 11, in <module>
2024-09-30T22:51:01.480795717Z     main(
2024-09-30T22:51:01.480996321Z   File "/full-model/fme/fme/ace/inference/evaluator.py", line 174, in main
2024-09-30T22:51:01.480998855Z     return run_evaluator_from_config(config)
2024-09-30T22:51:01.481194248Z   File "/full-model/fme/fme/ace/inference/evaluator.py", line 196, in run_evaluator_from_config
2024-09-30T22:51:01.481197125Z     data = get_inference_data(
2024-09-30T22:51:01.481396443Z   File "/full-model/fme/fme/core/data_loading/getters.py", line 162, in get_inference_data
2024-09-30T22:51:01.481400099Z     dataset = InferenceDataset(config, forward_steps_in_memory, requirements, ocean)
2024-09-30T22:51:01.481596486Z   File "/full-model/fme/fme/core/data_loading/inference.py", line 176, in __init__
2024-09-30T22:51:01.481599129Z     dataset = XarrayDataset(config.dataset, requirements=requirements)
2024-09-30T22:51:01.481795267Z   File "/full-model/fme/fme/core/data_loading/_xarray.py", line 307, in __init__
2024-09-30T22:51:01.481806770Z     self._get_files_stats(config.n_repeats, config.infer_timestep)
2024-09-30T22:51:01.482012796Z   File "/full-model/fme/fme/core/data_loading/_xarray.py", line 386, in _get_files_stats
2024-09-30T22:51:01.482026517Z     self._get_metadata(ds)
2024-09-30T22:51:01.482196271Z   File "/full-model/fme/fme/core/data_loading/_xarray.py", line 353, in _get_metadata
2024-09-30T22:51:01.482199851Z     elif hasattr(ds[name], "units") and hasattr(ds[name], "long_name"):
2024-09-30T22:51:01.482393095Z   File "/usr/local/lib/python3.10/dist-packages/xarray/core/dataset.py", line 1578, in __getitem__
2024-09-30T22:51:01.482396297Z     raise KeyError(
2024-09-30T22:51:01.482619291Z KeyError: "No variable named 'prescribed_qflux'. Variables on the dataset include ['DLWRFsfc', 'DSWRFsfc', 'DSWRFtoa', 'GRAUPELsfc', 'HGTsfc', ..., 'surface_temperature', 'tendency_of_total_water_path', 'tendency_of_total_water_path_due_to_advection', 'time', 'total_water_path']"
```

I believe this is due to the fact that we infer the `data_requirements` using the configuration loaded from the serialized stepper without taking into account the overriding ocean:

https://github.com/ai2cm/full-model/blob/1856538b0760a332b1e4641c600365ebd4abefc2/fme/fme/ace/inference/evaluator.py#L185-L194

i.e. `InferenceEvaluatorConfig.load_stepper_config` does not override the ocean configuration:

https://github.com/ai2cm/full-model/blob/1856538b0760a332b1e4641c600365ebd4abefc2/fme/fme/ace/inference/evaluator.py#L136-L138

We probably need a solution analogous to what is done in `InferenceEvaluatorConfig.load_stepper`.

**Comment by oliverwm1** [comment]
Ah yeah, that makes sense. Indeed should be straightforward enough to implement in the 'load config' function also. Ultimately we might want a more generic way to override options at inference-time, instead of implementing in a one-off way like we have for the ocean config.
