### ISSUE TITLE
500 year inference crashes in monthly calculation 150 steps before end

### ISSUE THREAD

**Issue by rebassoo** [ai2cm/ace#467]
When running a long run the standalone inference crashes in the batch starting at 37 days before the end with the error below. The crash is is calculating the updated monthly file. I have attached the config file though I couldn't attach a yaml file so attached it as a txt file.

```
2024-09-28 08:28:52,172 - root - INFO - Inference: starting window spanning 729850 to 729900 steps.
Traceback (most recent call last):
  File "/global/homes/r/rebassoo/.conda/envs/fme/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/global/homes/r/rebassoo/.conda/envs/fme/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/global/u2/r/rebassoo/work/fme/full-model/fme/fme/ace/inference/inference.py", line 303, in <module>
    main(yaml_config=args.yaml_config)
  File "/global/u2/r/rebassoo/work/fme/full-model/fme/fme/ace/inference/inference.py", line 209, in main
    return run_inference_from_config(config)
  File "/global/u2/r/rebassoo/work/fme/full-model/fme/fme/ace/inference/inference.py", line 261, in run_inference_from_config
    run_inference(
  File "/global/u2/r/rebassoo/work/fme/full-model/fme/fme/ace/inference/loop.py", line 295, in run_inference
    writer.append_batch(prediction, i_time, forward_times)
  File "/global/u2/r/rebassoo/work/fme/full-model/fme/fme/ace/inference/data_writer/main.py", line 389, in append_batch
    writer.append_batch(data, start_timestep, batch_times)
  File "/global/u2/r/rebassoo/work/fme/full-model/fme/fme/ace/inference/data_writer/monthly.py", line 281, in append_batch
    add_data(
  File "/global/u2/r/rebassoo/work/fme/full-model/fme/fme/ace/inference/data_writer/monthly.py", line 340, in add_data
    old_mean = target[i_sample, month_index]
  File "/global/homes/r/rebassoo/.conda/envs/fme/lib/python3.10/site-packages/numpy/ma/core.py", line 3228, in __getitem__
    dout = self.data[indx]
IndexError: index 1 is out of bounds for axis 1 with size 1
```

[config.txt](https://github.com/user-attachments/files/17262484/config.txt)

**Comment by oliverwm1** [comment]
I wonder if this is related to ai2cm/ace#279.
