### ISSUE TITLE
Inference error: `AttributeError: Can't pickle local object 'get_atmospheric_batch_data.<locals>._derive_func`

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#478]
I had an [inference job](https://beaker.org/ex/01JBHYAEJN0X0GHG9MB2Q9Q0FZ/tasks/01JBHYAEJT63T66K11GEY0QNNF/job/01JBHYAEQFJKKAJAJKVGQN87JR) that recently failed with this error:

```
2024-10-31T18:46:10.683605556Z 2024-10-31 18:46:10,683 - root - INFO - Multiprocessing inference context: forkserver
2024-10-31T18:46:54.290967780Z Traceback (most recent call last):
2024-10-31T18:46:54.291030941Z   File "/usr/lib/python3.10/multiprocessing/queues.py", line 244, in _feed
2024-10-31T18:46:54.291035821Z     obj = _ForkingPickler.dumps(obj)
2024-10-31T18:46:54.291040031Z   File "/usr/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
2024-10-31T18:46:54.291044211Z     cls(buf, protocol).dump(obj)
2024-10-31T18:46:54.291047751Z AttributeError: Can't pickle local object 'get_atmospheric_batch_data.<locals>._derive_func'
```

**Comment by oliverwm1** [comment]
This may be a general issue with multiprocessing, or it may be specific to the fact that this inference run was using forkserver because it was loading from zarr on GCS.

**Comment by oliverwm1** [comment]
FYI @mcgibbon it may be worth having at least one unit test that uses `num_workers>0`. I'm not sure if this is reproducible that way, but I suspect it might be.

**Comment by oliverwm1** [comment]
Note, when I switched to using netCDFs for the forcing data (which means we no longer use forkserver) then this error went away. Also tagging @frodre for visibility.

**Comment by jpdunc23** [comment]
I encountered this error just now in a training job on an [experimental branch](https://github.com/ai2cm/full-model/pull/1305). My data is all in netcdfs, so not sure why this is cropping up for me:

```
2024-10-31 12:19:01,330 - root - INFO - Horizontal coordinate sizes are {'lat': 180, 'lon': 360}.
2024-10-31 12:19:01,405 - root - INFO - The required variables have been found in the dataset: ['thetao_17', 'tauuo', 'uo_2', 'uo_6', 'zos', 'thetao_8', 'so_17', 'so_10', 'thetao_5', 'so_14', 'uo_8', 'uo_10', 'vo_9', 'vo_8', 'so_6', 'so_11', 'uo_3', 'uo_12', 'thetao_3', 'vo_6', 'vo_7', 'vo_15', 'uo_4', 'thetao_4', 'so_5', 'so_2', 'thetao_6', 'thetao_11', 'vo_11', 'so_18', 'uo_5', 'so_12', 'thetao_7', 'so_8', 'so_15', 'thetao_18', 'thetao_12', 'vo_2', 'vo_3', 'thetao_14', 'tauvo', 'vo_16', 'thetao_10', 'vo_0', 'vo_4', 'uo_14', 'uo_17', 'uo_0', 'thetao_1', 'uo_1', 'uo_9', 'so_4', 'vo_14', 'so_3', 'thetao_15', 'vo_18', 'uo_16', 'vo_12', 'uo_15', 'so_0', 'thetao_16', 'so_13', 'thetao_2', 'uo_13', 'uo_18', 'vo_5', 'so_9', 'thetao_9', 'so_7', 'thetao_13', 'thetao_0', 'vo_10', 'so_1', 'vo_17', 'so_16', 'uo_7', 'uo_11', 'hfds', 'vo_1', 'vo_13'].
2024-10-31 12:19:01,406 - fme.core.data_loading._xarray - WARNING - Dataset does not contain ak and bk coordinates.
2024-10-31 12:19:01,409 - root - INFO - Multiprocessing inference context: fork
Traceback (most recent call last):
  File "/global/common/software/m4492/fme-env/d1f5d60/lib/python3.10/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/global/common/software/m4492/fme-env/d1f5d60/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
AttributeError: Can't pickle local object 'get_atmospheric_batch_data.<locals>._derive_func'
```

**Comment by mcgibbon** [comment]
Made a PR I think will resolve the issue, but I don't have a unit test yet.

**Comment by mcgibbon** [comment]
OK I made a failing unit test and I don't think the PR will resolve the issue. Working on a fix.

The issue is that the `collate_fn` argument to `DataLoader` init gets picked to send to other workers, so this function can't be defined locally. I think it has to be defined at the module level or as a method of a pickleable class.

**Comment by mcgibbon** [comment]
Issue should now be resolved by the PR. Would be ideal to test in production. The test fails if I were to use a locally defined (in the function) `def collate_fn`, as such functions can't be pickled.

Well actually, it doesn't fail - unfortunately it would hang indefinitely. I wanted to include a "fail" test demonstrating the failure but I couldn't figure out a way to do this without the test itself hanging.

**Comment by oliverwm1** [comment]
I also saw a hang in my production run (after the Traceback got printed) where I saw the issue originally, FWIW.

**Comment by oliverwm1** [comment]
I guess if it hangs long enough, it will fail due to our timeout rules?

**Comment by mcgibbon** [comment]
Yeah but the "assert it fails" test needs to not actually fail (which it would if it times out). In the end I opted to just not include such a test. But if the real test is "failing" (hangs) then yes, it will fail due to the timeout rules.
