### ISSUE TITLE
wandb runs are not continuous for beaker jobs that get preempted

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#67]
It is very useful to be able to run our jobs as ["preemptible"](https://beaker-docs.apps.allenai.org/management.html#preemption) since this allows us to run on any group's cluster and therefore opens up a lot of computing resources. This currently works (training jobs automatically restart after preemption) but the corresponding wandb runs are split across each segment of training. For example see [this run](https://wandb.ai/ai2cm/fourcastnet-era5/runs/4w1xc38k?workspace=user-oliverwm) which only has epochs 106-150. We should make sure wandb runs resume appropriately: https://docs.wandb.ai/guides/runs/resuming

**Comment by gideonite** [comment]
Checkpointing doesn't work at all. This issue is blocked until we can fix that. See [beaker log file](https://beaker.org/api/v3/jobs/01H0106MZJXJ29SHAGXHMAAKT3/logs?tail=2). 
```
2023-05-09T19:36:44.902684338Z Traceback (most recent call last):
2023-05-09T19:36:44.903043295Z   File "/full-model/fme/fme/fcn_training/train.py", line 994, in <module>
2023-05-09T19:36:44.903065985Z     main(
2023-05-09T19:36:44.903170624Z   File "/full-model/fme/fme/fcn_training/train.py", line 980, in main
2023-05-09T19:36:44.903184024Z     trainer = Trainer(params, params.world_rank)
2023-05-09T19:36:44.903266323Z   File "/full-model/fme/fme/fcn_training/train.py", line 540, in __init__
2023-05-09T19:36:44.903279373Z     self.restore_checkpoint(params.checkpoint_path)
2023-05-09T19:36:44.903354993Z   File "/full-model/fme/fme/fcn_training/train.py", line 938, in restore_checkpoint
2023-05-09T19:36:44.903367683Z     checkpoint = torch.load(
2023-05-09T19:36:44.903442542Z   File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 716, in load
2023-05-09T19:36:44.903455992Z     with _open_zipfile_reader(opened_file) as opened_zipfile:
2023-05-09T19:36:44.903580781Z   File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 252, in __init__
2023-05-09T19:36:44.903593161Z     super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
2023-05-09T19:36:44.903726470Z RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
2023-05-09T19:36:44.906126449Z wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
2023-05-09T19:36:48.436157440Z wandb: 🚀 View run dainty-silence-545 at: https://wandb.ai/ai2cm/fourcastnet-era5/runs/c7jssywo
2023-05-09T19:36:48.436206759Z wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
2023-05-09T19:36:48.436263949Z wandb: Find logs at: ./wandb/run-20230509_193641-c7jssywo/logs
2023-05-09T19:36:52.206960191Z ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 149) of binary: /opt/conda/bin/python
2023-05-09T19:36:52.211359124Z Traceback (most recent call last):
2023-05-09T19:36:52.211396073Z   File "/opt/conda/bin/torchrun", line 33, in <module>
2023-05-09T19:36:52.211400853Z     sys.exit(load_entry_point('torch==1.13.0a0+d321be6', 'console_scripts', 'torchrun')())
2023-05-09T19:36:52.211403833Z   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
2023-05-09T19:36:52.211407703Z     return f(*args, **kwargs)
2023-05-09T19:36:52.211410443Z   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 761, in main
2023-05-09T19:36:52.211413313Z     run(args)
2023-05-09T19:36:52.211416013Z   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
2023-05-09T19:36:52.211418903Z     elastic_launch(
2023-05-09T19:36:52.211421613Z   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
2023-05-09T19:36:52.211444393Z     return launch_agent(self._config, self._entrypoint, list(args))
2023-05-09T19:36:52.211447193Z   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
2023-05-09T19:36:52.211450293Z     raise ChildFailedError(
2023-05-09T19:36:52.211452803Z torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
2023-05-09T19:36:52.211455453Z ============================================================
2023-05-09T19:36:52.211458183Z /full-model/fme/fme/fcn_training/train.py FAILED
```

**Comment by gideonite** [comment]
@oliverwm1 have you seen this behavior before?

**Comment by gideonite** [comment]
Turns out there was a recent fix that remedies this! Thanks!

**Comment by gideonite** [comment]
Closed https://github.com/ai2cm/full-model/pull/82
